package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundBankCardBin;
import topdeep.commonfund.entity.db.FundBankCardBinExample;

public interface FundBankCardBinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int countByExample(FundBankCardBinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int deleteByExample(FundBankCardBinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int insert(FundBankCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int insertSelective(FundBankCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    List<FundBankCardBin> selectByExample(FundBankCardBinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    FundBankCardBin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundBankCardBin record, @Param("example") FundBankCardBinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundBankCardBin record, @Param("example") FundBankCardBinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundBankCardBin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bank_card_bin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundBankCardBin record);
}