package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundFundCatagoryFundRela;
import topdeep.commonfund.entity.db.FundFundCatagoryFundRelaExample;
import topdeep.commonfund.entity.db.FundFundCatagoryFundRelaKey;

public interface FundFundCatagoryFundRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int countByExample(FundFundCatagoryFundRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int deleteByExample(FundFundCatagoryFundRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FundFundCatagoryFundRelaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int insert(FundFundCatagoryFundRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int insertSelective(FundFundCatagoryFundRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    List<FundFundCatagoryFundRela> selectByExample(FundFundCatagoryFundRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    FundFundCatagoryFundRela selectByPrimaryKey(FundFundCatagoryFundRelaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundFundCatagoryFundRela record, @Param("example") FundFundCatagoryFundRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundFundCatagoryFundRela record, @Param("example") FundFundCatagoryFundRelaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundFundCatagoryFundRela record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_catagory_fund_rela
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundFundCatagoryFundRela record);
}