package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundBindInfo;
import topdeep.commonfund.entity.db.FundBindInfoExample;
import topdeep.commonfund.entity.db.FundBindInfoKey;

public interface FundBindInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int countByExample(FundBindInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int deleteByExample(FundBindInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FundBindInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int insert(FundBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int insertSelective(FundBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    List<FundBindInfo> selectByExample(FundBindInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    FundBindInfo selectByPrimaryKey(FundBindInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundBindInfo record, @Param("example") FundBindInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundBindInfo record, @Param("example") FundBindInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_bind_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundBindInfo record);
}