package topdeep.commonfund.entity.db;

import common.entity.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundCustomerLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public FundCustomerLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNull() {
            addCriterion("CUST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNotNull() {
            addCriterion("CUST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCustTypeEqualTo(String value) {
            addCriterion("CUST_TYPE =", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotEqualTo(String value) {
            addCriterion("CUST_TYPE <>", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThan(String value) {
            addCriterion("CUST_TYPE >", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE >=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThan(String value) {
            addCriterion("CUST_TYPE <", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE <=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLike(String value) {
            addCriterion("CUST_TYPE like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotLike(String value) {
            addCriterion("CUST_TYPE not like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeIn(List<String> values) {
            addCriterion("CUST_TYPE in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotIn(List<String> values) {
            addCriterion("CUST_TYPE not in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeBetween(String value1, String value2) {
            addCriterion("CUST_TYPE between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotBetween(String value1, String value2) {
            addCriterion("CUST_TYPE not between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNull() {
            addCriterion("CUSTOMER_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNotNull() {
            addCriterion("CUSTOMER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoEqualTo(String value) {
            addCriterion("CUSTOMER_NO =", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotEqualTo(String value) {
            addCriterion("CUSTOMER_NO <>", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThan(String value) {
            addCriterion("CUSTOMER_NO >", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_NO >=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThan(String value) {
            addCriterion("CUSTOMER_NO <", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_NO <=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLike(String value) {
            addCriterion("CUSTOMER_NO like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotLike(String value) {
            addCriterion("CUSTOMER_NO not like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIn(List<String> values) {
            addCriterion("CUSTOMER_NO in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotIn(List<String> values) {
            addCriterion("CUSTOMER_NO not in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoBetween(String value1, String value2) {
            addCriterion("CUSTOMER_NO between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_NO not between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNull() {
            addCriterion("ID_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNotNull() {
            addCriterion("ID_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIdTypeEqualTo(String value) {
            addCriterion("ID_TYPE =", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotEqualTo(String value) {
            addCriterion("ID_TYPE <>", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThan(String value) {
            addCriterion("ID_TYPE >", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_TYPE >=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThan(String value) {
            addCriterion("ID_TYPE <", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThanOrEqualTo(String value) {
            addCriterion("ID_TYPE <=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLike(String value) {
            addCriterion("ID_TYPE like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotLike(String value) {
            addCriterion("ID_TYPE not like", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeIn(List<String> values) {
            addCriterion("ID_TYPE in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotIn(List<String> values) {
            addCriterion("ID_TYPE not in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeBetween(String value1, String value2) {
            addCriterion("ID_TYPE between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotBetween(String value1, String value2) {
            addCriterion("ID_TYPE not between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNull() {
            addCriterion("ID_NO is null");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNotNull() {
            addCriterion("ID_NO is not null");
            return (Criteria) this;
        }

        public Criteria andIdNoEqualTo(String value) {
            addCriterion("ID_NO =", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotEqualTo(String value) {
            addCriterion("ID_NO <>", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThan(String value) {
            addCriterion("ID_NO >", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThanOrEqualTo(String value) {
            addCriterion("ID_NO >=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThan(String value) {
            addCriterion("ID_NO <", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThanOrEqualTo(String value) {
            addCriterion("ID_NO <=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLike(String value) {
            addCriterion("ID_NO like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotLike(String value) {
            addCriterion("ID_NO not like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoIn(List<String> values) {
            addCriterion("ID_NO in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotIn(List<String> values) {
            addCriterion("ID_NO not in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoBetween(String value1, String value2) {
            addCriterion("ID_NO between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotBetween(String value1, String value2) {
            addCriterion("ID_NO not between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andClientSrcIsNull() {
            addCriterion("CLIENT_SRC is null");
            return (Criteria) this;
        }

        public Criteria andClientSrcIsNotNull() {
            addCriterion("CLIENT_SRC is not null");
            return (Criteria) this;
        }

        public Criteria andClientSrcEqualTo(String value) {
            addCriterion("CLIENT_SRC =", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcNotEqualTo(String value) {
            addCriterion("CLIENT_SRC <>", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcGreaterThan(String value) {
            addCriterion("CLIENT_SRC >", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcGreaterThanOrEqualTo(String value) {
            addCriterion("CLIENT_SRC >=", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcLessThan(String value) {
            addCriterion("CLIENT_SRC <", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcLessThanOrEqualTo(String value) {
            addCriterion("CLIENT_SRC <=", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcLike(String value) {
            addCriterion("CLIENT_SRC like", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcNotLike(String value) {
            addCriterion("CLIENT_SRC not like", value, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcIn(List<String> values) {
            addCriterion("CLIENT_SRC in", values, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcNotIn(List<String> values) {
            addCriterion("CLIENT_SRC not in", values, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcBetween(String value1, String value2) {
            addCriterion("CLIENT_SRC between", value1, value2, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andClientSrcNotBetween(String value1, String value2) {
            addCriterion("CLIENT_SRC not between", value1, value2, "clientSrc");
            return (Criteria) this;
        }

        public Criteria andActionTimeIsNull() {
            addCriterion("ACTION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActionTimeIsNotNull() {
            addCriterion("ACTION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActionTimeEqualTo(Date value) {
            addCriterion("ACTION_TIME =", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotEqualTo(Date value) {
            addCriterion("ACTION_TIME <>", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeGreaterThan(Date value) {
            addCriterion("ACTION_TIME >", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ACTION_TIME >=", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeLessThan(Date value) {
            addCriterion("ACTION_TIME <", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeLessThanOrEqualTo(Date value) {
            addCriterion("ACTION_TIME <=", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeIn(List<Date> values) {
            addCriterion("ACTION_TIME in", values, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotIn(List<Date> values) {
            addCriterion("ACTION_TIME not in", values, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeBetween(Date value1, Date value2) {
            addCriterion("ACTION_TIME between", value1, value2, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotBetween(Date value1, Date value2) {
            addCriterion("ACTION_TIME not between", value1, value2, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTypeIsNull() {
            addCriterion("ACTION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andActionTypeIsNotNull() {
            addCriterion("ACTION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andActionTypeEqualTo(String value) {
            addCriterion("ACTION_TYPE =", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotEqualTo(String value) {
            addCriterion("ACTION_TYPE <>", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeGreaterThan(String value) {
            addCriterion("ACTION_TYPE >", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_TYPE >=", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLessThan(String value) {
            addCriterion("ACTION_TYPE <", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLessThanOrEqualTo(String value) {
            addCriterion("ACTION_TYPE <=", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeLike(String value) {
            addCriterion("ACTION_TYPE like", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotLike(String value) {
            addCriterion("ACTION_TYPE not like", value, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeIn(List<String> values) {
            addCriterion("ACTION_TYPE in", values, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotIn(List<String> values) {
            addCriterion("ACTION_TYPE not in", values, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeBetween(String value1, String value2) {
            addCriterion("ACTION_TYPE between", value1, value2, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionTypeNotBetween(String value1, String value2) {
            addCriterion("ACTION_TYPE not between", value1, value2, "actionType");
            return (Criteria) this;
        }

        public Criteria andActionParam1IsNull() {
            addCriterion("ACTION_PARAM1 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam1IsNotNull() {
            addCriterion("ACTION_PARAM1 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam1EqualTo(String value) {
            addCriterion("ACTION_PARAM1 =", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1NotEqualTo(String value) {
            addCriterion("ACTION_PARAM1 <>", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1GreaterThan(String value) {
            addCriterion("ACTION_PARAM1 >", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM1 >=", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1LessThan(String value) {
            addCriterion("ACTION_PARAM1 <", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM1 <=", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1Like(String value) {
            addCriterion("ACTION_PARAM1 like", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1NotLike(String value) {
            addCriterion("ACTION_PARAM1 not like", value, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1In(List<String> values) {
            addCriterion("ACTION_PARAM1 in", values, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1NotIn(List<String> values) {
            addCriterion("ACTION_PARAM1 not in", values, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1Between(String value1, String value2) {
            addCriterion("ACTION_PARAM1 between", value1, value2, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam1NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM1 not between", value1, value2, "actionParam1");
            return (Criteria) this;
        }

        public Criteria andActionParam2IsNull() {
            addCriterion("ACTION_PARAM2 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam2IsNotNull() {
            addCriterion("ACTION_PARAM2 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam2EqualTo(String value) {
            addCriterion("ACTION_PARAM2 =", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2NotEqualTo(String value) {
            addCriterion("ACTION_PARAM2 <>", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2GreaterThan(String value) {
            addCriterion("ACTION_PARAM2 >", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM2 >=", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2LessThan(String value) {
            addCriterion("ACTION_PARAM2 <", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM2 <=", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2Like(String value) {
            addCriterion("ACTION_PARAM2 like", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2NotLike(String value) {
            addCriterion("ACTION_PARAM2 not like", value, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2In(List<String> values) {
            addCriterion("ACTION_PARAM2 in", values, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2NotIn(List<String> values) {
            addCriterion("ACTION_PARAM2 not in", values, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2Between(String value1, String value2) {
            addCriterion("ACTION_PARAM2 between", value1, value2, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam2NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM2 not between", value1, value2, "actionParam2");
            return (Criteria) this;
        }

        public Criteria andActionParam3IsNull() {
            addCriterion("ACTION_PARAM3 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam3IsNotNull() {
            addCriterion("ACTION_PARAM3 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam3EqualTo(String value) {
            addCriterion("ACTION_PARAM3 =", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3NotEqualTo(String value) {
            addCriterion("ACTION_PARAM3 <>", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3GreaterThan(String value) {
            addCriterion("ACTION_PARAM3 >", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM3 >=", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3LessThan(String value) {
            addCriterion("ACTION_PARAM3 <", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM3 <=", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3Like(String value) {
            addCriterion("ACTION_PARAM3 like", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3NotLike(String value) {
            addCriterion("ACTION_PARAM3 not like", value, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3In(List<String> values) {
            addCriterion("ACTION_PARAM3 in", values, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3NotIn(List<String> values) {
            addCriterion("ACTION_PARAM3 not in", values, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3Between(String value1, String value2) {
            addCriterion("ACTION_PARAM3 between", value1, value2, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam3NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM3 not between", value1, value2, "actionParam3");
            return (Criteria) this;
        }

        public Criteria andActionParam4IsNull() {
            addCriterion("ACTION_PARAM4 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam4IsNotNull() {
            addCriterion("ACTION_PARAM4 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam4EqualTo(String value) {
            addCriterion("ACTION_PARAM4 =", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4NotEqualTo(String value) {
            addCriterion("ACTION_PARAM4 <>", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4GreaterThan(String value) {
            addCriterion("ACTION_PARAM4 >", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM4 >=", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4LessThan(String value) {
            addCriterion("ACTION_PARAM4 <", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM4 <=", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4Like(String value) {
            addCriterion("ACTION_PARAM4 like", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4NotLike(String value) {
            addCriterion("ACTION_PARAM4 not like", value, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4In(List<String> values) {
            addCriterion("ACTION_PARAM4 in", values, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4NotIn(List<String> values) {
            addCriterion("ACTION_PARAM4 not in", values, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4Between(String value1, String value2) {
            addCriterion("ACTION_PARAM4 between", value1, value2, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam4NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM4 not between", value1, value2, "actionParam4");
            return (Criteria) this;
        }

        public Criteria andActionParam5IsNull() {
            addCriterion("ACTION_PARAM5 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam5IsNotNull() {
            addCriterion("ACTION_PARAM5 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam5EqualTo(String value) {
            addCriterion("ACTION_PARAM5 =", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5NotEqualTo(String value) {
            addCriterion("ACTION_PARAM5 <>", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5GreaterThan(String value) {
            addCriterion("ACTION_PARAM5 >", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM5 >=", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5LessThan(String value) {
            addCriterion("ACTION_PARAM5 <", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM5 <=", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5Like(String value) {
            addCriterion("ACTION_PARAM5 like", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5NotLike(String value) {
            addCriterion("ACTION_PARAM5 not like", value, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5In(List<String> values) {
            addCriterion("ACTION_PARAM5 in", values, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5NotIn(List<String> values) {
            addCriterion("ACTION_PARAM5 not in", values, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5Between(String value1, String value2) {
            addCriterion("ACTION_PARAM5 between", value1, value2, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam5NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM5 not between", value1, value2, "actionParam5");
            return (Criteria) this;
        }

        public Criteria andActionParam6IsNull() {
            addCriterion("ACTION_PARAM6 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam6IsNotNull() {
            addCriterion("ACTION_PARAM6 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam6EqualTo(String value) {
            addCriterion("ACTION_PARAM6 =", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6NotEqualTo(String value) {
            addCriterion("ACTION_PARAM6 <>", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6GreaterThan(String value) {
            addCriterion("ACTION_PARAM6 >", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM6 >=", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6LessThan(String value) {
            addCriterion("ACTION_PARAM6 <", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM6 <=", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6Like(String value) {
            addCriterion("ACTION_PARAM6 like", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6NotLike(String value) {
            addCriterion("ACTION_PARAM6 not like", value, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6In(List<String> values) {
            addCriterion("ACTION_PARAM6 in", values, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6NotIn(List<String> values) {
            addCriterion("ACTION_PARAM6 not in", values, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6Between(String value1, String value2) {
            addCriterion("ACTION_PARAM6 between", value1, value2, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam6NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM6 not between", value1, value2, "actionParam6");
            return (Criteria) this;
        }

        public Criteria andActionParam7IsNull() {
            addCriterion("ACTION_PARAM7 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam7IsNotNull() {
            addCriterion("ACTION_PARAM7 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam7EqualTo(String value) {
            addCriterion("ACTION_PARAM7 =", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7NotEqualTo(String value) {
            addCriterion("ACTION_PARAM7 <>", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7GreaterThan(String value) {
            addCriterion("ACTION_PARAM7 >", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM7 >=", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7LessThan(String value) {
            addCriterion("ACTION_PARAM7 <", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM7 <=", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7Like(String value) {
            addCriterion("ACTION_PARAM7 like", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7NotLike(String value) {
            addCriterion("ACTION_PARAM7 not like", value, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7In(List<String> values) {
            addCriterion("ACTION_PARAM7 in", values, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7NotIn(List<String> values) {
            addCriterion("ACTION_PARAM7 not in", values, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7Between(String value1, String value2) {
            addCriterion("ACTION_PARAM7 between", value1, value2, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam7NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM7 not between", value1, value2, "actionParam7");
            return (Criteria) this;
        }

        public Criteria andActionParam8IsNull() {
            addCriterion("ACTION_PARAM8 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam8IsNotNull() {
            addCriterion("ACTION_PARAM8 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam8EqualTo(String value) {
            addCriterion("ACTION_PARAM8 =", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8NotEqualTo(String value) {
            addCriterion("ACTION_PARAM8 <>", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8GreaterThan(String value) {
            addCriterion("ACTION_PARAM8 >", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM8 >=", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8LessThan(String value) {
            addCriterion("ACTION_PARAM8 <", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM8 <=", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8Like(String value) {
            addCriterion("ACTION_PARAM8 like", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8NotLike(String value) {
            addCriterion("ACTION_PARAM8 not like", value, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8In(List<String> values) {
            addCriterion("ACTION_PARAM8 in", values, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8NotIn(List<String> values) {
            addCriterion("ACTION_PARAM8 not in", values, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8Between(String value1, String value2) {
            addCriterion("ACTION_PARAM8 between", value1, value2, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam8NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM8 not between", value1, value2, "actionParam8");
            return (Criteria) this;
        }

        public Criteria andActionParam9IsNull() {
            addCriterion("ACTION_PARAM9 is null");
            return (Criteria) this;
        }

        public Criteria andActionParam9IsNotNull() {
            addCriterion("ACTION_PARAM9 is not null");
            return (Criteria) this;
        }

        public Criteria andActionParam9EqualTo(String value) {
            addCriterion("ACTION_PARAM9 =", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9NotEqualTo(String value) {
            addCriterion("ACTION_PARAM9 <>", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9GreaterThan(String value) {
            addCriterion("ACTION_PARAM9 >", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9GreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM9 >=", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9LessThan(String value) {
            addCriterion("ACTION_PARAM9 <", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9LessThanOrEqualTo(String value) {
            addCriterion("ACTION_PARAM9 <=", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9Like(String value) {
            addCriterion("ACTION_PARAM9 like", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9NotLike(String value) {
            addCriterion("ACTION_PARAM9 not like", value, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9In(List<String> values) {
            addCriterion("ACTION_PARAM9 in", values, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9NotIn(List<String> values) {
            addCriterion("ACTION_PARAM9 not in", values, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9Between(String value1, String value2) {
            addCriterion("ACTION_PARAM9 between", value1, value2, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andActionParam9NotBetween(String value1, String value2) {
            addCriterion("ACTION_PARAM9 not between", value1, value2, "actionParam9");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("ROW_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("ROW_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Integer value) {
            addCriterion("ROW_VERSION =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Integer value) {
            addCriterion("ROW_VERSION <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Integer value) {
            addCriterion("ROW_VERSION >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROW_VERSION >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Integer value) {
            addCriterion("ROW_VERSION <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Integer value) {
            addCriterion("ROW_VERSION <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Integer> values) {
            addCriterion("ROW_VERSION in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Integer> values) {
            addCriterion("ROW_VERSION not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Integer value1, Integer value2) {
            addCriterion("ROW_VERSION between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("ROW_VERSION not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}