package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundCustomerLog;
import topdeep.commonfund.entity.db.FundCustomerLogExample;

public interface FundCustomerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int countByExample(FundCustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int deleteByExample(FundCustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int insert(FundCustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int insertSelective(FundCustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    List<FundCustomerLog> selectByExample(FundCustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    FundCustomerLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundCustomerLog record, @Param("example") FundCustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundCustomerLog record, @Param("example") FundCustomerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundCustomerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundCustomerLog record);
}