package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundFundProperty;
import topdeep.commonfund.entity.db.FundFundPropertyExample;
import topdeep.commonfund.entity.db.FundFundPropertyKey;

public interface FundFundPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int countByExample(FundFundPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int deleteByExample(FundFundPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FundFundPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int insert(FundFundProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int insertSelective(FundFundProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    List<FundFundProperty> selectByExample(FundFundPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    FundFundProperty selectByPrimaryKey(FundFundPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundFundProperty record, @Param("example") FundFundPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundFundProperty record, @Param("example") FundFundPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundFundProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_fund_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundFundProperty record);
}