package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundCustomerPassword;
import topdeep.commonfund.entity.db.FundCustomerPasswordExample;

public interface FundCustomerPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int countByExample(FundCustomerPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int deleteByExample(FundCustomerPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int insert(FundCustomerPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int insertSelective(FundCustomerPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    List<FundCustomerPassword> selectByExample(FundCustomerPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    FundCustomerPassword selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundCustomerPassword record, @Param("example") FundCustomerPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundCustomerPassword record, @Param("example") FundCustomerPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundCustomerPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_customer_password
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundCustomerPassword record);
}