package topdeep.commonfund.entity.db;

import java.util.Date;
import topdeep.commonfund.entity.base.BaseEntity;

public class FundTradeParamConvert extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.PARAM_TYPE
     *
     * @mbggenerated
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.PAY_SEAT_NO
     *
     * @mbggenerated
     */
    private String paySeatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.SEAT_NO
     *
     * @mbggenerated
     */
    private String seatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.BANK_NO
     *
     * @mbggenerated
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.LOCAL_VALUE
     *
     * @mbggenerated
     */
    private String localValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.BANK_VALUE
     *
     * @mbggenerated
     */
    private String bankValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.AUDIT_STATE
     *
     * @mbggenerated
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.AUDIT_NAME
     *
     * @mbggenerated
     */
    private String auditName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.AUDIT_ID
     *
     * @mbggenerated
     */
    private String auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.AUDIT_TIME
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.MODIFY_NAME
     *
     * @mbggenerated
     */
    private String modifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.ROW_VERSION
     *
     * @mbggenerated
     */
    private Integer rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.CREATE_ID
     *
     * @mbggenerated
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.CREATE_NAME
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund_trade_param_convert.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    public FundTradeParamConvert(String id, String paramType, String paySeatNo, String seatNo, String bankNo, String localValue, String bankValue, String auditState, String auditName, String auditId, Date auditTime, String modifyName, Integer rowVersion, Date createTime, String createId, String createName, Date modifyTime, String modifyId) {
        this.id = id;
        this.paramType = paramType;
        this.paySeatNo = paySeatNo;
        this.seatNo = seatNo;
        this.bankNo = bankNo;
        this.localValue = localValue;
        this.bankValue = bankValue;
        this.auditState = auditState;
        this.auditName = auditName;
        this.auditId = auditId;
        this.auditTime = auditTime;
        this.modifyName = modifyName;
        this.rowVersion = rowVersion;
        this.createTime = createTime;
        this.createId = createId;
        this.createName = createName;
        this.modifyTime = modifyTime;
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    public FundTradeParamConvert() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.ID
     *
     * @return the value of t_fund_trade_param_convert.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.ID
     *
     * @param id the value for t_fund_trade_param_convert.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.PARAM_TYPE
     *
     * @return the value of t_fund_trade_param_convert.PARAM_TYPE
     *
     * @mbggenerated
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.PARAM_TYPE
     *
     * @param paramType the value for t_fund_trade_param_convert.PARAM_TYPE
     *
     * @mbggenerated
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.PAY_SEAT_NO
     *
     * @return the value of t_fund_trade_param_convert.PAY_SEAT_NO
     *
     * @mbggenerated
     */
    public String getPaySeatNo() {
        return paySeatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.PAY_SEAT_NO
     *
     * @param paySeatNo the value for t_fund_trade_param_convert.PAY_SEAT_NO
     *
     * @mbggenerated
     */
    public void setPaySeatNo(String paySeatNo) {
        this.paySeatNo = paySeatNo == null ? null : paySeatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.SEAT_NO
     *
     * @return the value of t_fund_trade_param_convert.SEAT_NO
     *
     * @mbggenerated
     */
    public String getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.SEAT_NO
     *
     * @param seatNo the value for t_fund_trade_param_convert.SEAT_NO
     *
     * @mbggenerated
     */
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo == null ? null : seatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.BANK_NO
     *
     * @return the value of t_fund_trade_param_convert.BANK_NO
     *
     * @mbggenerated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.BANK_NO
     *
     * @param bankNo the value for t_fund_trade_param_convert.BANK_NO
     *
     * @mbggenerated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.LOCAL_VALUE
     *
     * @return the value of t_fund_trade_param_convert.LOCAL_VALUE
     *
     * @mbggenerated
     */
    public String getLocalValue() {
        return localValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.LOCAL_VALUE
     *
     * @param localValue the value for t_fund_trade_param_convert.LOCAL_VALUE
     *
     * @mbggenerated
     */
    public void setLocalValue(String localValue) {
        this.localValue = localValue == null ? null : localValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.BANK_VALUE
     *
     * @return the value of t_fund_trade_param_convert.BANK_VALUE
     *
     * @mbggenerated
     */
    public String getBankValue() {
        return bankValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.BANK_VALUE
     *
     * @param bankValue the value for t_fund_trade_param_convert.BANK_VALUE
     *
     * @mbggenerated
     */
    public void setBankValue(String bankValue) {
        this.bankValue = bankValue == null ? null : bankValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.AUDIT_STATE
     *
     * @return the value of t_fund_trade_param_convert.AUDIT_STATE
     *
     * @mbggenerated
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.AUDIT_STATE
     *
     * @param auditState the value for t_fund_trade_param_convert.AUDIT_STATE
     *
     * @mbggenerated
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.AUDIT_NAME
     *
     * @return the value of t_fund_trade_param_convert.AUDIT_NAME
     *
     * @mbggenerated
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.AUDIT_NAME
     *
     * @param auditName the value for t_fund_trade_param_convert.AUDIT_NAME
     *
     * @mbggenerated
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.AUDIT_ID
     *
     * @return the value of t_fund_trade_param_convert.AUDIT_ID
     *
     * @mbggenerated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.AUDIT_ID
     *
     * @param auditId the value for t_fund_trade_param_convert.AUDIT_ID
     *
     * @mbggenerated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId == null ? null : auditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.AUDIT_TIME
     *
     * @return the value of t_fund_trade_param_convert.AUDIT_TIME
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.AUDIT_TIME
     *
     * @param auditTime the value for t_fund_trade_param_convert.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.MODIFY_NAME
     *
     * @return the value of t_fund_trade_param_convert.MODIFY_NAME
     *
     * @mbggenerated
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.MODIFY_NAME
     *
     * @param modifyName the value for t_fund_trade_param_convert.MODIFY_NAME
     *
     * @mbggenerated
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.ROW_VERSION
     *
     * @return the value of t_fund_trade_param_convert.ROW_VERSION
     *
     * @mbggenerated
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.ROW_VERSION
     *
     * @param rowVersion the value for t_fund_trade_param_convert.ROW_VERSION
     *
     * @mbggenerated
     */
    public void setRowVersion(Integer rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.CREATE_TIME
     *
     * @return the value of t_fund_trade_param_convert.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.CREATE_TIME
     *
     * @param createTime the value for t_fund_trade_param_convert.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.CREATE_ID
     *
     * @return the value of t_fund_trade_param_convert.CREATE_ID
     *
     * @mbggenerated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.CREATE_ID
     *
     * @param createId the value for t_fund_trade_param_convert.CREATE_ID
     *
     * @mbggenerated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.CREATE_NAME
     *
     * @return the value of t_fund_trade_param_convert.CREATE_NAME
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.CREATE_NAME
     *
     * @param createName the value for t_fund_trade_param_convert.CREATE_NAME
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.MODIFY_TIME
     *
     * @return the value of t_fund_trade_param_convert.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.MODIFY_TIME
     *
     * @param modifyTime the value for t_fund_trade_param_convert.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund_trade_param_convert.MODIFY_ID
     *
     * @return the value of t_fund_trade_param_convert.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund_trade_param_convert.MODIFY_ID
     *
     * @param modifyId the value for t_fund_trade_param_convert.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }
}