package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.FundTradeParamConvert;
import topdeep.commonfund.entity.db.FundTradeParamConvertExample;

public interface FundTradeParamConvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int countByExample(FundTradeParamConvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int deleteByExample(FundTradeParamConvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int insert(FundTradeParamConvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int insertSelective(FundTradeParamConvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    List<FundTradeParamConvert> selectByExample(FundTradeParamConvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    FundTradeParamConvert selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FundTradeParamConvert record, @Param("example") FundTradeParamConvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FundTradeParamConvert record, @Param("example") FundTradeParamConvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FundTradeParamConvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_trade_param_convert
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FundTradeParamConvert record);
}