package topdeep.commonfund.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.commonfund.entity.db.VFundFundCategoryFund;
import topdeep.commonfund.entity.db.VFundFundCategoryFundExample;

public interface VFundFundCategoryFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int countByExample(VFundFundCategoryFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int deleteByExample(VFundFundCategoryFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int insert(VFundFundCategoryFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int insertSelective(VFundFundCategoryFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    List<VFundFundCategoryFund> selectByExample(VFundFundCategoryFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VFundFundCategoryFund record, @Param("example") VFundFundCategoryFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_fund_fund_category_fund
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VFundFundCategoryFund record, @Param("example") VFundFundCategoryFundExample example);
}