ALTER TABLE T_SYSTEM_VALID_INFO drop column VALID_USER_ID;
ALTER TABLE T_SYSTEM_VALID_INFO drop column VALID_TYPE;

ALTER TABLE T_SYSTEM_VALID_INFO ADD (
   VALID_USER_ID_TYPE   VARCHAR2(100)                   NOT NULL,
   VALID_USER_ID_NO     VARCHAR2(100)                   NOT NULL,
   VALID_TYPE           CHAR(1)                         NOT NULL
);

COMMENT ON COLUMN T_SYSTEM_VALID_INFO.VALID_USER_ID_TYPE IS
'验证的用户标识类型';

COMMENT ON COLUMN T_SYSTEM_VALID_INFO.VALID_USER_ID_NO IS
'验证的用户标识';

COMMENT ON COLUMN T_SYSTEM_VALID_INFO.VALID_TYPE IS
'验证类型 0 用户邮箱验证 1 忘记密码验证';

update T_SYSTEM_CONFIG set SYSTEM_PARAM_VALUE = '1.5', MODIFY_TIME = sysdate where SYSTEM_PARAM_CATEGORY = 'topdeep.common.entity.params.CommonDbParam' and SYSTEM_PARAM_CODE = 'dbVersion';

commit;