/*==============================================================*/
/* Table: T_SYSTEM_CLIENT_ACTIVATION                            */
/*==============================================================*/
CREATE TABLE T_SYSTEM_CLIENT_ACTIVATION  (
   ID                   CHAR(24)                        NOT NULL,
   CHANNEL              VARCHAR2(50)                    NOT NULL,
   CLIENT_TYPE          VARCHAR2(50)                    NOT NULL,
   CLIENT_VERSION       VARCHAR2(50)                    NOT NULL,
   DEVICE_ID            VARCHAR2(100)                   NOT NULL,
   PUSH_ID              VARCHAR2(100),
   ACTIVATION_TIME      DATE                            NOT NULL,
   CLIENT_MODEL         VARCHAR2(200),
   CLIENT_OS            VARCHAR2(200),
   CLIENT_OS_VERSION    VARCHAR2(200),
   CLIENT_NETWORK_TYPE  VARCHAR2(200),
   CLIENT_NETWORK_EXTRA_INFO VARCHAR2(200),
   CLIENT_SCREEN_WIDTH  VARCHAR2(200),
   CLIENT_SCREEN_HEIGHT VARCHAR2(200),
   CLIENT_SCREEN_DENSITY VARCHAR2(200),
   STATE                CHAR(1)                         NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_SYSTEM_CLIENT_ACTIVATION PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_CLIENT_ACTIVATION IS
'客户端激活表';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.ID IS
'PK';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CHANNEL IS
'激活渠道';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_TYPE IS
'客户端类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_VERSION IS
'客户端版本';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.DEVICE_ID IS
'设备标识';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.PUSH_ID IS
'用于推送的标识';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.ACTIVATION_TIME IS
'激活时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_MODEL IS
'设备型号';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_OS IS
'客户端操作系统';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_OS_VERSION IS
'客户端操作系统版本';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_NETWORK_TYPE IS
'客户端网络类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_NETWORK_EXTRA_INFO IS
'客户端网络扩展信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_SCREEN_WIDTH IS
'客户端屏幕宽度';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_SCREEN_HEIGHT IS
'客户端屏幕高度';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.CLIENT_SCREEN_DENSITY IS
'客户端屏幕密度';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.STATE IS
'0 无效 1有效，表示最后激活的相同设备';

COMMENT ON COLUMN T_SYSTEM_CLIENT_ACTIVATION.ROW_VERSION IS
'版本';

/*==============================================================*/
/* Table: T_SYSTEM_CLIENT_TRACK                                 */
/*==============================================================*/
CREATE TABLE T_SYSTEM_CLIENT_TRACK  (
   ID                   CHAR(24)                        NOT NULL,
   CLIENT_VERSION       VARCHAR2(50)                    NOT NULL,
   CLIENT_TYPE          VARCHAR2(50)                    NOT NULL,
   DEVICE_ID            VARCHAR2(50)                    NOT NULL,
   TRACK_API            VARCHAR2(50)                    NOT NULL,
   TRACK_TYPE           VARCHAR2(200)                   NOT NULL,
   TRACK_ID             VARCHAR2(200)                   NOT NULL,
   CLIENT_NETWORK_EXTRA_INFO VARCHAR2(200),
   CLIENT_NETWORK_TYPE  VARCHAR2(200),
   TIMESTAMP            NUMBER(18)                      NOT NULL,
   USE_TIME             NUMBER(8,0)                     NOT NULL,
   PUB1                 VARCHAR2(200),
   PUB2                 VARCHAR2(200),
   PUB3                 VARCHAR2(200),
   PUB4                 VARCHAR2(200),
   PUB5                 VARCHAR2(200),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_SYSTEM_CLIENT_TRACK PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_CLIENT_TRACK IS
'客户端行为追踪表';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.ID IS
'PK';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.CLIENT_VERSION IS
'客户端版本';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.CLIENT_TYPE IS
'客户端类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.DEVICE_ID IS
'设备标识';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.TRACK_API IS
'TRACK_API_VERSION';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.TRACK_TYPE IS
'跟踪类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.TRACK_ID IS
'跟踪关键字';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.CLIENT_NETWORK_EXTRA_INFO IS
'客户端网络扩展信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.CLIENT_NETWORK_TYPE IS
'客户端网络类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.TIMESTAMP IS
'JAVATIMESTAMP';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.USE_TIME IS
'跟踪用的时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.PUB1 IS
'备用信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.PUB2 IS
'备用信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.PUB3 IS
'备用信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.PUB4 IS
'备用信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.PUB5 IS
'备用信息';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK.ROW_VERSION IS
'版本';


/*==============================================================*/
/* Table: T_SYSTEM_CLIENT_TRACK_DETAIL                          */
/*==============================================================*/
CREATE TABLE T_SYSTEM_CLIENT_TRACK_DETAIL  (
   ID                   CHAR(24)                        NOT NULL,
   TRACK_ID             CHAR(24)                        NOT NULL,
   DETAIL_KEY           VARCHAR2(200)                   NOT NULL,
   DETAIL_VALUE         VARCHAR2(2000),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_SYSTEM_CLIENT_TRACK_DETAI PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_CLIENT_TRACK_DETAIL IS
'客户端追踪明细';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK_DETAIL.ID IS
'PK';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK_DETAIL.TRACK_ID IS
'FK';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK_DETAIL.DETAIL_KEY IS
'明细Key';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK_DETAIL.DETAIL_VALUE IS
'明细Value';

COMMENT ON COLUMN T_SYSTEM_CLIENT_TRACK_DETAIL.ROW_VERSION IS
'版本';


/*==============================================================*/
/* Table: T_SYSTEM_CLIENT_VERSION                               */
/*==============================================================*/
CREATE TABLE T_SYSTEM_CLIENT_VERSION  (
   CLIENT_TYPE          VARCHAR2(50)                    NOT NULL,
   CLIENT_VERSION       VARCHAR2(50)                    NOT NULL,
   CLIENT_STATE         CHAR(1)                         NOT NULL,
   RELEASE_TIME         DATE                            NOT NULL,
   CLIENT_SIGNATURE     VARCHAR2(200),
   CURRENT_INSTALL_URL  VARCHAR2(500),
   NEXT_UPDATE_URL      VARCHAR2(500),
   CLIENT_ENCRYPT_KEY   VARCHAR2(100)                   NOT NULL,
   CLIENT_SIGN_KEY      VARCHAR2(100)                   NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_SYSTEM_CLIENT_VERSION PRIMARY KEY (CLIENT_TYPE, CLIENT_VERSION)
);

COMMENT ON TABLE T_SYSTEM_CLIENT_VERSION IS
'客户端版本控制';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_TYPE IS
'客户端类型';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_VERSION IS
'客户端版本';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_STATE IS
'客户端状态,0 版本最新，允许运行 1 版本已旧，但允许继续运行 2 版本过旧，不允许运行，必须升级';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.RELEASE_TIME IS
'客户端发布时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_SIGNATURE IS
'客户端签名';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CURRENT_INSTALL_URL IS
'当前版本的下载地址';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.NEXT_UPDATE_URL IS
'升级版本的下载地址';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_ENCRYPT_KEY IS
'客户端加密Key';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CLIENT_SIGN_KEY IS
'客户端签名Key';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_SYSTEM_CLIENT_VERSION.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_SYSTEM_HIS_MSG_PUSH_DETAIL                          */
/*==============================================================*/
CREATE TABLE T_SYSTEM_HIS_MSG_PUSH_DETAIL  (
   ID                   CHAR(24)                        NOT NULL,
   TASK_ID              CHAR(24)                        NOT NULL,
   PUSH_ID              VARCHAR2(50),
   APP_TYPE             CHAR(1),
   READ_STATE           CHAR(1)                        DEFAULT '0',
   SEND_STATE           CHAR(1),
   SEND_NUM             NUMBER(8,0),
   FIRST_SEND_TIME      DATE,
   LAST_SEND_TIME       DATE,
   FAILURE_REASON       VARCHAR2(50),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   DELETED              CHAR(1)                        DEFAULT '0' NOT NULL,
   AUDIT_STATE          CHAR(1),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_ID             CHAR(24),
   AUDIT_TIME           DATE,
   CONSTRAINT PK_T_SYSTEM_HIS_MSG_PUSH_DETAI PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_HIS_MSG_PUSH_DETAIL IS
'消息推送任务内容表LOG表';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.ID IS
'主键ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.TASK_ID IS
'推送批次ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.PUSH_ID IS
'推送目标ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.APP_TYPE IS
'手机类型 1. 安卓 2. ios';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.READ_STATE IS
'阅读状态0：未读， 1:已读';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.SEND_STATE IS
'推送状态0:未推送, 1 :推送中, 2:推送成功 ;3:推送响应失败;  ';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.SEND_NUM IS
'已经推送次数';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.FIRST_SEND_TIME IS
'失败推送时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.LAST_SEND_TIME IS
'本次推送时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.FAILURE_REASON IS
'推送失败原因';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_TIME IS
'审核时间';


/*==============================================================*/
/* Table: T_SYSTEM_HIS_MSG_PUSH_TASK                            */
/*==============================================================*/
CREATE TABLE T_SYSTEM_HIS_MSG_PUSH_TASK  (
   ID                   CHAR(24)                        NOT NULL,
   TITLE                VARCHAR2(50),
   CLIENT_APP           VARCHAR2(50)                    NOT NULL,
   START_DATE           DATE,
   END_DATE             DATE,
   START_TIME           VARCHAR2(50),
   END_TIME             VARCHAR2(50),
   SEND_TYPE            CHAR(1),
   RESEND_TYPE          CHAR(1),
   RESEND_NUM           NUMBER(8,0),
   RESEND_INTERVALS     NUMBER(8,0),
   MESSAGE              VARCHAR2(500),
   MESSAGE_TYPE         CHAR(1),
   CHANNEL_ID           CHAR(1),
   DELETED              CHAR(1)                        DEFAULT '0' NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_ID             CHAR(24),
   AUDIT_TIME           DATE,
   CONSTRAINT PK_T_SYSTEM_HIS_MSG_PUSH_TASK PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_HIS_MSG_PUSH_TASK IS
'消息推送任务表LOG表';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.ID IS
'主键ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.TITLE IS
'标题';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.CLIENT_APP IS
'客户端应用类型';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.START_DATE IS
'开始日期';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.END_DATE IS
'结束日期';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.START_TIME IS
'开始时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.END_TIME IS
'结束时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.SEND_TYPE IS
'发送状态0：未发送，1：发送队列中 2：等待下次发送 3：发送成功';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_TYPE IS
'是否失败重复发送 0 ：否   ， 1：是';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_NUM IS
'重复执行次数';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_INTERVALS IS
'重复执行间隔 单位分钟';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.MESSAGE IS
'推送内容';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.MESSAGE_TYPE IS
'推送内容类型1. 新闻 2 . 生日祝福';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.CHANNEL_ID IS
'推送渠道 1: 手机APP  2 : 微信';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_TIME IS
'审核时间';


/*==============================================================*/
/* Table: T_SYSTEM_MSG_PUSH_DETAIL                              */
/*==============================================================*/
CREATE TABLE T_SYSTEM_MSG_PUSH_DETAIL  (
   ID                   CHAR(24)                        NOT NULL,
   TASK_ID              CHAR(24)                        NOT NULL,
   PUSH_ID              VARCHAR2(100),
   APP_TYPE             CHAR(1),
   READ_STATE           CHAR(1)                        DEFAULT '0',
   SEND_STATE           CHAR(1),
   SEND_NUM             NUMBER(8,0),
   FIRST_SEND_TIME      DATE,
   LAST_SEND_TIME       DATE,
   FAILURE_REASON       VARCHAR2(50),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   DELETED              CHAR(1)                        DEFAULT '0' NOT NULL,
   AUDIT_STATE          CHAR(1),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_ID             CHAR(24),
   AUDIT_TIME           DATE,
   CONSTRAINT PK_T_SYSTEM_MSG_PUSH_DETAIL PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_MSG_PUSH_DETAIL IS
'消息推送任务内容表';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.ID IS
'主键ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.TASK_ID IS
'推送批次ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.PUSH_ID IS
'推送目标ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.APP_TYPE IS
'手机类型 1. 安卓 2. ios';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.READ_STATE IS
'阅读状态0：未读， 1:已读';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.SEND_STATE IS
'推送状态0:未推送, 1 :推送中, 2:推送成功 ;3:推送响应失败;  ';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.SEND_NUM IS
'已经推送次数';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.FIRST_SEND_TIME IS
'失败推送时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.LAST_SEND_TIME IS
'本次推送时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.FAILURE_REASON IS
'推送失败原因';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_TIME IS
'审核时间';

/*==============================================================*/
/* Table: T_SYSTEM_MSG_PUSH_TASK                                */
/*==============================================================*/
CREATE TABLE T_SYSTEM_MSG_PUSH_TASK  (
   ID                   CHAR(24)                        NOT NULL,
   TITLE                VARCHAR2(50),
   CLIENT_APP           VARCHAR2(50)                    NOT NULL,
   START_DATE           DATE,
   END_DATE             DATE,
   START_TIME           VARCHAR2(50),
   END_TIME             VARCHAR2(50),
   SEND_TARGET_TYPE     CHAR(1)                         NOT NULL,
   SEND_TYPE            CHAR(1),
   RESEND_TYPE          CHAR(1),
   RESEND_NUM           NUMBER(8,0),
   RESEND_INTERVALS     NUMBER(8,0),
   MESSAGE              VARCHAR2(500),
   MESSAGE_TYPE         CHAR(1)                         NOT NULL,
   MESSAGE_PARAM        VARCHAR2(255),
   CHANNEL_ID           CHAR(1),
   DELETED              CHAR(1)                        DEFAULT '0' NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_SYSTEM_MSG_PUSH_TASK PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_MSG_PUSH_TASK IS
'消息推送任务表';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.ID IS
'主键ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.TITLE IS
'标题';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.CLIENT_APP IS
'客户端应用类型';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.START_DATE IS
'开始日期';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.END_DATE IS
'结束日期';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.START_TIME IS
'开始时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.END_TIME IS
'结束时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.SEND_TARGET_TYPE IS
'0 all 1指定用户 2 android 3iphone';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.SEND_TYPE IS
'发送状态0：未发送，1,：发送中 2：等待下次发送 3：发送成功';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.RESEND_TYPE IS
'是否失败重复发送 0 ：否   ， 1：是';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.RESEND_NUM IS
'重复执行次数';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.RESEND_INTERVALS IS
'重复执行间隔 单位分钟';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MESSAGE IS
'推送内容';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MESSAGE_TYPE IS
'0 普通消息提示1内链2外链';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MESSAGE_PARAM IS
'0无，1、2链接地址';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.CHANNEL_ID IS
'推送渠道 1: 手机APP  2 : 微信';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_SYSTEM_MSG_PUSH_TASK.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_SYSTEM_VISIT_LOG                                    */
/*==============================================================*/
CREATE TABLE T_SYSTEM_VISIT_LOG  (
   ID                   CHAR(24)                        NOT NULL,
   VISIT_SRC            VARCHAR2(50)                    NOT NULL,
   OPENID               VARCHAR2(100),
   CHANNEL              VARCHAR2(50),
   SRC_VERSION          VARCHAR2(50),
   CLIENT_TYPE          VARCHAR2(50),
   OS                   VARCHAR2(50),
   OS_VERSION           VARCHAR2(50),
   NETWORK              VARCHAR2(50),
   SERVICE              VARCHAR2(50),
   MOBILE_PHONE         VARCHAR2(50),
   SCREEN               VARCHAR2(50),
   OTHER                VARCHAR2(500),
   LOG_SESSION_ID       VARCHAR2(100),
   LOG_IP               VARCHAR2(50),
   LOG_UA               VARCHAR2(500),
   LOG_REFER_URL        VARCHAR2(500),
   LOG_URL              VARCHAR2(500),
   LOG_PARAM            VARCHAR2(1000),
   LOG_TIME             DATE                            NOT NULL,
   VISIT_RESULT         CHAR(1)                         NOT NULL,
   VISIT_FAIL_REASON    VARCHAR2(500),
   VISIT_RESULT_VIEW    VARCHAR2(100),
   PROCESS_TIME         NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_SYSTEM_VISIT_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE T_SYSTEM_VISIT_LOG IS
'客户端访问用户日志';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.ID IS
'标识';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.VISIT_SRC IS
'访问来源';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.OPENID IS
'客户端标识,如果是纯网页用户，则用服务器生成的currency_visiter_id代替';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.CHANNEL IS
'渠道';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.SRC_VERSION IS
'版本';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.CLIENT_TYPE IS
'手机类型';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.OS IS
'iphone,android';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.OS_VERSION IS
'操作系统版本';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.NETWORK IS
'wifi|2g|3g|4g';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.SERVICE IS
'0中国移动1中国联通2中国电信';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.MOBILE_PHONE IS
'手机号码';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.SCREEN IS
'屏幕大小';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.OTHER IS
'其它参数';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_SESSION_ID IS
'访问SessionID';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_IP IS
'访问IP';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_UA IS
'访问UA';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_REFER_URL IS
'引用URL';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_URL IS
'访问URL';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_PARAM IS
'访问全部参数';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.LOG_TIME IS
'访问时间';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.VISIT_RESULT IS
'访问是否成功 0 成功 1 失败';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.VISIT_FAIL_REASON IS
'访问失败原因';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.VISIT_RESULT_VIEW IS
'访问结果模板';

COMMENT ON COLUMN T_SYSTEM_VISIT_LOG.PROCESS_TIME IS
'处理时间';


/*==============================================================*/
/* View: V_SYSTEM_MSG_PUSH_DETAIL                               */
/*==============================================================*/
CREATE OR REPLACE VIEW V_SYSTEM_MSG_PUSH_DETAIL AS
SELECT
   T_SYSTEM_MSG_PUSH_DETAIL.ID,
   T_SYSTEM_MSG_PUSH_DETAIL.TASK_ID,
   T_SYSTEM_MSG_PUSH_DETAIL.PUSH_ID,
   T_SYSTEM_MSG_PUSH_DETAIL.APP_TYPE,
   T_SYSTEM_MSG_PUSH_DETAIL.READ_STATE,
   T_SYSTEM_MSG_PUSH_DETAIL.SEND_STATE,
   T_SYSTEM_MSG_PUSH_DETAIL.SEND_NUM,
   T_SYSTEM_MSG_PUSH_DETAIL.FIRST_SEND_TIME,
   T_SYSTEM_MSG_PUSH_DETAIL.LAST_SEND_TIME,
   T_SYSTEM_MSG_PUSH_DETAIL.FAILURE_REASON,
   T_SYSTEM_MSG_PUSH_DETAIL.ROW_VERSION,
   T_SYSTEM_MSG_PUSH_DETAIL.CREATE_TIME,
   T_SYSTEM_MSG_PUSH_DETAIL.CREATE_ID,
   T_SYSTEM_MSG_PUSH_DETAIL.CREATE_NAME,
   T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_TIME,
   T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_ID,
   T_SYSTEM_MSG_PUSH_DETAIL.MODIFY_NAME,
   T_SYSTEM_MSG_PUSH_DETAIL.DELETED,
   T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_STATE,
   T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_NAME,
   T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_ID,
   T_SYSTEM_MSG_PUSH_DETAIL.AUDIT_TIME
FROM
   T_SYSTEM_MSG_PUSH_DETAIL
 UNION  ALL
SELECT
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.TASK_ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.PUSH_ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.APP_TYPE,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.READ_STATE,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.SEND_STATE,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.SEND_NUM,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.FIRST_SEND_TIME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.LAST_SEND_TIME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.FAILURE_REASON,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.ROW_VERSION,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_TIME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.CREATE_NAME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_TIME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.MODIFY_NAME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.DELETED,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_STATE,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_NAME,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_ID,
   T_SYSTEM_HIS_MSG_PUSH_DETAIL.AUDIT_TIME
FROM
   T_SYSTEM_HIS_MSG_PUSH_DETAIL
WITH READ ONLY;

 COMMENT ON TABLE V_SYSTEM_MSG_PUSH_DETAIL IS
'推送信息详细表与历史表合并显示';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.ID IS
'主键ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.TASK_ID IS
'推送批次ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.PUSH_ID IS
'推送目标ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.APP_TYPE IS
'手机类型 1. 安卓 2. ios';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.READ_STATE IS
'阅读状态0：未读， 1:已读';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.SEND_STATE IS
'推送状态0:未推送, 1 :推送中, 2:推送成功 ;3:推送响应失败;  ';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.SEND_NUM IS
'已经推送次数';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.FIRST_SEND_TIME IS
'失败推送时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.LAST_SEND_TIME IS
'本次推送时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.FAILURE_REASON IS
'推送失败原因';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.ROW_VERSION IS
'版本';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_DETAIL.AUDIT_TIME IS
'审核时间';



/*==============================================================*/
/* View: V_SYSTEM_MSG_PUSH_TASK                                 */
/*==============================================================*/
CREATE OR REPLACE VIEW V_SYSTEM_MSG_PUSH_TASK AS
SELECT
   T_SYSTEM_MSG_PUSH_TASK.ID,
   T_SYSTEM_MSG_PUSH_TASK.TITLE,
   T_SYSTEM_MSG_PUSH_TASK.CLIENT_APP,
   T_SYSTEM_MSG_PUSH_TASK.START_DATE,
   T_SYSTEM_MSG_PUSH_TASK.END_DATE,
   T_SYSTEM_MSG_PUSH_TASK.START_TIME,
   T_SYSTEM_MSG_PUSH_TASK.END_TIME,
   T_SYSTEM_MSG_PUSH_TASK.SEND_TYPE,
   T_SYSTEM_MSG_PUSH_TASK.RESEND_TYPE,
   T_SYSTEM_MSG_PUSH_TASK.RESEND_NUM,
   T_SYSTEM_MSG_PUSH_TASK.RESEND_INTERVALS,
   T_SYSTEM_MSG_PUSH_TASK.MESSAGE,
   T_SYSTEM_MSG_PUSH_TASK.MESSAGE_TYPE,
   T_SYSTEM_MSG_PUSH_TASK.CHANNEL_ID,
   T_SYSTEM_MSG_PUSH_TASK.DELETED,
   T_SYSTEM_MSG_PUSH_TASK.ROW_VERSION,
   T_SYSTEM_MSG_PUSH_TASK.CREATE_TIME,
   T_SYSTEM_MSG_PUSH_TASK.CREATE_ID,
   T_SYSTEM_MSG_PUSH_TASK.CREATE_NAME,
   T_SYSTEM_MSG_PUSH_TASK.MODIFY_TIME,
   T_SYSTEM_MSG_PUSH_TASK.MODIFY_ID,
   T_SYSTEM_MSG_PUSH_TASK.MODIFY_NAME,
   T_SYSTEM_MSG_PUSH_TASK.AUDIT_TIME,
   T_SYSTEM_MSG_PUSH_TASK.AUDIT_ID,
   T_SYSTEM_MSG_PUSH_TASK.AUDIT_NAME,
   T_SYSTEM_MSG_PUSH_TASK.AUDIT_STATE
FROM
   T_SYSTEM_MSG_PUSH_TASK
UNION
SELECT
   T_SYSTEM_HIS_MSG_PUSH_TASK.ID,
   T_SYSTEM_HIS_MSG_PUSH_TASK.TITLE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.CLIENT_APP,
   T_SYSTEM_HIS_MSG_PUSH_TASK.START_DATE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.END_DATE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.START_TIME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.END_TIME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.SEND_TYPE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_TYPE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_NUM,
   T_SYSTEM_HIS_MSG_PUSH_TASK.RESEND_INTERVALS,
   T_SYSTEM_HIS_MSG_PUSH_TASK.MESSAGE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.MESSAGE_TYPE,
   T_SYSTEM_HIS_MSG_PUSH_TASK.CHANNEL_ID,
   T_SYSTEM_HIS_MSG_PUSH_TASK.DELETED,
   T_SYSTEM_HIS_MSG_PUSH_TASK.ROW_VERSION,
   T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_TIME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_ID,
   T_SYSTEM_HIS_MSG_PUSH_TASK.CREATE_NAME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_TIME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_ID,
   T_SYSTEM_HIS_MSG_PUSH_TASK.MODIFY_NAME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_TIME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_ID,
   T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_NAME,
   T_SYSTEM_HIS_MSG_PUSH_TASK.AUDIT_STATE
FROM
   T_SYSTEM_HIS_MSG_PUSH_TASK
WITH READ ONLY;

 COMMENT ON TABLE V_SYSTEM_MSG_PUSH_TASK IS
'推送任务表与历史表合并显示';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.ID IS
'主键ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.TITLE IS
'标题';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.CLIENT_APP IS
'客户端应用类型';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.START_DATE IS
'开始日期';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.END_DATE IS
'结束日期';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.START_TIME IS
'开始时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.END_TIME IS
'结束时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.SEND_TYPE IS
'发送状态0：未发送，1,：发送中 2：等待下次发送 3：发送成功';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.RESEND_TYPE IS
'是否失败重复发送 0 ：否   ， 1：是';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.RESEND_NUM IS
'重复执行次数';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.RESEND_INTERVALS IS
'重复执行间隔 单位分钟';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.MESSAGE IS
'推送内容';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.MESSAGE_TYPE IS
'0 普通消息提示1内链2外链';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.CHANNEL_ID IS
'推送渠道 1: 手机APP  2 : 微信';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.DELETED IS
'0未删除1删除';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.ROW_VERSION IS
'版本';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN V_SYSTEM_MSG_PUSH_TASK.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';



drop table T_HIS_MESSAGE_PUSH_TASK;
drop table T_HIS_MESSAGE_PUSH_TASK_DETAIL;
drop table T_MESSAGE_PUSH_TASK;
drop table T_MESSAGE_PUSH_TASK_DETAIL;

drop view V_MESSAGE_PUSH_TASK;
drop view V_MESSAGE_PUSH_TASK_DETAIL;





update T_SYSTEM_CONFIG set SYSTEM_PARAM_VALUE = '1.4', MODIFY_TIME = sysdate where SYSTEM_PARAM_CATEGORY = 'topdeep.common.entity.params.CommonDbParam' and SYSTEM_PARAM_CODE = 'dbVersion';

commit;