
/*==============================================================*/
/* Table: T_FUND_BIND_INFO                                      */
/*==============================================================*/
CREATE TABLE T_FUND_BIND_INFO  (
   BIND_SRC             CHAR(1)                         NOT NULL,
   OPENID               VARCHAR2(50)                    NOT NULL,
   BIND_FLAG            CHAR(1)                         NOT NULL,
   OPEN_TRADE           CHAR(1)                         NOT NULL,
   BIND_TIME            DATE,
   UNBIND_TIME          DATE,
   LAST_VISIT_TIME      DATE                            NOT NULL,
   VISIT_COUNT          NUMBER(8,0)                     NOT NULL,
   CUST_NAME            VARCHAR2(100),
   CUST_SEX             CHAR(1),
   CHANNEL              VARCHAR2(50),
   ID_TYPE              VARCHAR2(50),
   ID_NO                VARCHAR2(50),
   SRC_VERSION          VARCHAR2(50),
   CLIENT_TYPE          VARCHAR2(50),
   OS                   VARCHAR2(50),
   OS_VERSION           VARCHAR2(50),
   NETWORK              VARCHAR2(50),
   SERVICE              VARCHAR2(50),
   MOBILE_PHONE         VARCHAR2(50),
   SCREEN               VARCHAR2(50),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CONSTRAINT PK_T_FUND_BIND_INFO PRIMARY KEY (BIND_SRC, OPENID)
);

COMMENT ON TABLE T_FUND_BIND_INFO IS
'绑定信息表';

COMMENT ON COLUMN T_FUND_BIND_INFO.BIND_SRC IS
'来源';

COMMENT ON COLUMN T_FUND_BIND_INFO.OPENID IS
'用户在来源系统中的标识';

COMMENT ON COLUMN T_FUND_BIND_INFO.BIND_FLAG IS
'标识 0 未绑定 1 绑定';

COMMENT ON COLUMN T_FUND_BIND_INFO.OPEN_TRADE IS
'是否开通直销账号 0 未开通 1 开通';

COMMENT ON COLUMN T_FUND_BIND_INFO.BIND_TIME IS
'绑定时间';

COMMENT ON COLUMN T_FUND_BIND_INFO.UNBIND_TIME IS
'解绑时间';

COMMENT ON COLUMN T_FUND_BIND_INFO.LAST_VISIT_TIME IS
'最后访问时间';

COMMENT ON COLUMN T_FUND_BIND_INFO.VISIT_COUNT IS
'访问次数';

COMMENT ON COLUMN T_FUND_BIND_INFO.CUST_NAME IS
'客户姓名';

COMMENT ON COLUMN T_FUND_BIND_INFO.CUST_SEX IS
'客户姓别1男2女';

COMMENT ON COLUMN T_FUND_BIND_INFO.CHANNEL IS
'渠道，绑定的渠道';

COMMENT ON COLUMN T_FUND_BIND_INFO.ID_TYPE IS
'证件类型';

COMMENT ON COLUMN T_FUND_BIND_INFO.ID_NO IS
'证件号码';

COMMENT ON COLUMN T_FUND_BIND_INFO.SRC_VERSION IS
'来源系统版本';

COMMENT ON COLUMN T_FUND_BIND_INFO.CLIENT_TYPE IS
'手机类型';

COMMENT ON COLUMN T_FUND_BIND_INFO.OS IS
'iphone,android';

COMMENT ON COLUMN T_FUND_BIND_INFO.OS_VERSION IS
'操作系统版本';

COMMENT ON COLUMN T_FUND_BIND_INFO.NETWORK IS
'wifi|2g|3g|4g';

COMMENT ON COLUMN T_FUND_BIND_INFO.SERVICE IS
'0中国移动1中国联通2中国电信';

COMMENT ON COLUMN T_FUND_BIND_INFO.MOBILE_PHONE IS
'手机号码';

COMMENT ON COLUMN T_FUND_BIND_INFO.SCREEN IS
'屏幕大小';

COMMENT ON COLUMN T_FUND_BIND_INFO.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_BIND_INFO.CREATE_TIME IS
'创建时间';

/*==============================================================*/
/* Table: T_FUND_CLIENT_ACTIVATION                              */
/*==============================================================*/
CREATE TABLE T_FUND_CLIENT_ACTIVATION  (
   ID                   CHAR(24)                        NOT NULL,
   CHANNEL              VARCHAR2(50)                    NOT NULL,
   CLIENT_TYPE          VARCHAR2(50)                    NOT NULL,
   CLIENT_VERSION       VARCHAR2(50)                    NOT NULL,
   DEVICE_ID            VARCHAR2(100)                   NOT NULL,
   PUSH_ID              VARCHAR2(100),
   ACTIVATION_TIME      DATE                            NOT NULL,
   CLIENT_MODEL         VARCHAR2(200),
   CLIENT_OS            VARCHAR2(200),
   CLIENT_OS_VERSION    VARCHAR2(200),
   CLIENT_NETWORK_TYPE  VARCHAR2(200),
   CLIENT_NETWORK_EXTRA_INFO VARCHAR2(200),
   CLIENT_SCREEN_WIDTH  VARCHAR2(200),
   CLIENT_SCREEN_HEIGHT VARCHAR2(200),
   CLIENT_SCREEN_DENSITY VARCHAR2(200),
   STATE                CHAR(1)                         NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_FUND_CLIENT_ACTIVATION PRIMARY KEY (ID)
);

COMMENT ON TABLE T_FUND_CLIENT_ACTIVATION IS
'客户端激活表';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.ID IS
'PK';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CHANNEL IS
'激活渠道';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_TYPE IS
'客户端类型';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_VERSION IS
'客户端版本';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.DEVICE_ID IS
'设备标识';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.PUSH_ID IS
'用于推送的标识';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.ACTIVATION_TIME IS
'激活时间';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_MODEL IS
'设备型号';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_OS IS
'客户端操作系统';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_OS_VERSION IS
'客户端操作系统版本';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_NETWORK_TYPE IS
'客户端网络类型';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_NETWORK_EXTRA_INFO IS
'客户端网络扩展信息';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_SCREEN_WIDTH IS
'客户端屏幕宽度';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_SCREEN_HEIGHT IS
'客户端屏幕高度';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.CLIENT_SCREEN_DENSITY IS
'客户端屏幕密度';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.STATE IS
'0 无效 1有效，表示最后激活的相同设备';

COMMENT ON COLUMN T_FUND_CLIENT_ACTIVATION.ROW_VERSION IS
'版本';

/*==============================================================*/
/* Table: T_FUND_CLIENT_VERSION                                 */
/*==============================================================*/
CREATE TABLE T_FUND_CLIENT_VERSION  (
   CLIENT_TYPE          VARCHAR2(50)                    NOT NULL,
   CLIENT_VERSION       VARCHAR2(50)                    NOT NULL,
   CLIENT_STATE         CHAR(1)                         NOT NULL,
   RELEASE_TIME         DATE                            NOT NULL,
   CLIENT_SIGNATURE     VARCHAR2(200),
   CURRENT_INSTALL_URL  VARCHAR2(500),
   NEXT_UPDATE_URL      VARCHAR2(500),
   CLIENT_ENCRYPT_KEY   VARCHAR2(100)                   NOT NULL,
   CLIENT_SIGN_KEY      VARCHAR2(100)                   NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_FUND_CLIENT_VERSION PRIMARY KEY (CLIENT_TYPE, CLIENT_VERSION)
);

COMMENT ON TABLE T_FUND_CLIENT_VERSION IS
'客户端版本控制';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_TYPE IS
'客户端类型';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_VERSION IS
'客户端版本';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_STATE IS
'客户端状态,0 版本最新，允许运行 1 版本已旧，但允许继续运行 2 版本过旧，不允许运行，必须升级';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.RELEASE_TIME IS
'客户端发布时间';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_SIGNATURE IS
'客户端签名';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CURRENT_INSTALL_URL IS
'当前版本的下载地址';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.NEXT_UPDATE_URL IS
'升级版本的下载地址';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_ENCRYPT_KEY IS
'客户端加密Key';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CLIENT_SIGN_KEY IS
'客户端签名Key';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_CLIENT_VERSION.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_FUND_CUSTOMER_LOG                                   */
/*==============================================================*/
CREATE TABLE T_FUND_CUSTOMER_LOG  (
   ID                   CHAR(24)                        NOT NULL,
   CUST_TYPE            CHAR(1)                        DEFAULT '1' NOT NULL,
   CUSTOMER_NO          VARCHAR2(100)                   NOT NULL,
   ID_TYPE              CHAR(1)                         NOT NULL,
   ID_NO                VARCHAR2(50)                    NOT NULL,
   CLIENT_SRC           VARCHAR2(50)                    NOT NULL,
   ACTION_TIME          DATE                            NOT NULL,
   ACTION_TYPE          VARCHAR2(50)                    NOT NULL,
   ACTION_PARAM1        VARCHAR2(100),
   ACTION_PARAM2        VARCHAR2(100),
   ACTION_PARAM3        VARCHAR2(100),
   ACTION_PARAM4        VARCHAR2(100),
   ACTION_PARAM5        VARCHAR2(100),
   ACTION_PARAM6        VARCHAR2(100),
   ACTION_PARAM7        VARCHAR2(100),
   ACTION_PARAM8        VARCHAR2(100),
   ACTION_PARAM9        VARCHAR2(100),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CONSTRAINT PK_T_FUND_CUSTOMER_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE T_FUND_CUSTOMER_LOG IS
'客户端用户记录
记录的操作包括：
1 登录操作
2 买入操作
3 卖出操作
4 撤单操作
5 开户操作
6 增卡操作';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ID IS
'主键';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.CUST_TYPE IS
'0机构 1个人';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.CUSTOMER_NO IS
'客户编号';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ID_TYPE IS
'客户证件类型';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ID_NO IS
'客户证件号码';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.CLIENT_SRC IS
'来源';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_TIME IS
'访问时间';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_TYPE IS
'动作类型 login purchase subscribe redeem cancel';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM1 IS
'参数1';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM2 IS
'参数2';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM3 IS
'参数3';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM4 IS
'参数4';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM5 IS
'参数5';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM6 IS
'参数6';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM7 IS
'参数7';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM8 IS
'参数8';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ACTION_PARAM9 IS
'参数9';

COMMENT ON COLUMN T_FUND_CUSTOMER_LOG.ROW_VERSION IS
'版本';

/*==============================================================*/
/* Table: T_FUND_EC_TRADE_SEAT                                  */
/*==============================================================*/
CREATE TABLE T_FUND_EC_TRADE_SEAT  (
   ID                   CHAR(24)                        NOT NULL,
   PAY_SEAT_NO          VARCHAR2(50)                    NOT NULL,
   PAY_SEAT_NAME        VARCHAR2(50)                    NOT NULL,
   BANK_NO              VARCHAR2(50)                    NOT NULL,
   BANK_NAME            VARCHAR2(50)                    NOT NULL,
   SEAT_NO              VARCHAR2(50)                    NOT NULL,
   SEAT_NAME            VARCHAR2(50)                    NOT NULL,
   SEAT_STATE           CHAR(1)                         NOT NULL,
   ORDER_FIELD          DATE                            NOT NULL,
   FINATYPE             CHAR(1)                         NOT NULL,
   EXT_ID               VARCHAR2(100),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   DELETED              CHAR(1)                        DEFAULT '0' NOT NULL,
   CONSTRAINT PK_T_FUND_EC_TRADE_SEAT PRIMARY KEY (ID)
);

COMMENT ON TABLE T_FUND_EC_TRADE_SEAT IS
'直销交易渠道';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.ID IS
'PK';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.PAY_SEAT_NO IS
'支付渠道代码';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.PAY_SEAT_NAME IS
'支付渠道名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.BANK_NO IS
'银行代码';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.BANK_NAME IS
'银行名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.SEAT_NO IS
'渠道代码';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.SEAT_NAME IS
'渠道名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.SEAT_STATE IS
'渠道状态';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.ORDER_FIELD IS
'排序字段，日期越新越排在前面';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.FINATYPE IS
'资金方式';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.EXT_ID IS
'直销渠道在外部系统的ID';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN T_FUND_EC_TRADE_SEAT.DELETED IS
'0未删除1删除';

/*==============================================================*/
/* Table: T_FUND_FUND_CATAGORY_FUND_RELA                        */
/*==============================================================*/
CREATE TABLE T_FUND_FUND_CATAGORY_FUND_RELA  (
   CATEGORY_ID          CHAR(24)                        NOT NULL,
   FUND_CODE            CHAR(6)                         NOT NULL,
   ORDER_FIELD          DATE                            NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_FUND_FUND_CATAGORY_FUND_R PRIMARY KEY (CATEGORY_ID, FUND_CODE)
);

COMMENT ON TABLE T_FUND_FUND_CATAGORY_FUND_RELA IS
'分类基金关联表';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.CATEGORY_ID IS
'分类标识';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.FUND_CODE IS
'基金代码';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.ORDER_FIELD IS
'排序';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_FUND_CATAGORY_FUND_RELA.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_FUND_FUND_CATEGORY                                  */
/*==============================================================*/
CREATE TABLE T_FUND_FUND_CATEGORY  (
   ID                   CHAR(24)                        NOT NULL,
   CATEGORY_NAME        VARCHAR2(100)                   NOT NULL,
   ORDER_FIELD          DATE                            NOT NULL,
   PARENT_ID            CHAR(24)                        NOT NULL,
   CATEGORY_STATE       CHAR(1)                         NOT NULL,
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_FUND_FUND_CATEGORY PRIMARY KEY (ID)
);

COMMENT ON TABLE T_FUND_FUND_CATEGORY IS
'基金显示分类';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.ID IS
'分类ID';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.CATEGORY_NAME IS
'分类名称';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.ORDER_FIELD IS
'排序字段';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.PARENT_ID IS
'父分类，没有父分类为24*';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.CATEGORY_STATE IS
'分类状态0不显示1显示';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_FUND_CATEGORY.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_FUND_FUND_INFO                                      */
/*==============================================================*/
CREATE TABLE T_FUND_FUND_INFO  (
   FUND_CODE            CHAR(6)                         NOT NULL,
   FUND_NAME            VARCHAR2(100)                   NOT NULL,
   FUND_FULL_NAME       VARCHAR2(200),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_FUND_FUND_INFO PRIMARY KEY (FUND_CODE)
);

COMMENT ON TABLE T_FUND_FUND_INFO IS
'基金信息';

COMMENT ON COLUMN T_FUND_FUND_INFO.FUND_CODE IS
'基金代码';

COMMENT ON COLUMN T_FUND_FUND_INFO.FUND_NAME IS
'基金简称';

COMMENT ON COLUMN T_FUND_FUND_INFO.FUND_FULL_NAME IS
'基金全称';

COMMENT ON COLUMN T_FUND_FUND_INFO.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_FUND_INFO.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_FUND_INFO.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_FUND_INFO.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_FUND_INFO.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_FUND_INFO.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_FUND_INFO.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_FUND_INFO.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_FUND_INFO.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_FUND_INFO.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_FUND_INFO.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_FUND_FUND_PROPERTY                                  */
/*==============================================================*/
CREATE TABLE T_FUND_FUND_PROPERTY  (
   FUND_CODE            CHAR(6)                         NOT NULL,
   PROPERTY_TYPE        VARCHAR2(50)                    NOT NULL,
   PROPERTY_VALUE       VARCHAR2(2000),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   MODIFY_NAME          VARCHAR2(100),
   AUDIT_TIME           DATE,
   AUDIT_ID             CHAR(24),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_STATE          CHAR(1),
   CONSTRAINT PK_T_FUND_FUND_PROPERTY PRIMARY KEY (FUND_CODE, PROPERTY_TYPE)
);

COMMENT ON TABLE T_FUND_FUND_PROPERTY IS
'基金属性表';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.FUND_CODE IS
'基金代码';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.PROPERTY_TYPE IS
'属性类型,枚举常量';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.PROPERTY_VALUE IS
'属性值';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.MODIFY_ID IS
'修改人ID';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_FUND_PROPERTY.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

/*==============================================================*/
/* Table: T_FUND_TRADE_PARAM_CONVERT                            */
/*==============================================================*/
CREATE TABLE T_FUND_TRADE_PARAM_CONVERT  (
   ID                   CHAR(24)                        NOT NULL,
   PARAM_TYPE           VARCHAR2(50)                    NOT NULL,
   PAY_SEAT_NO          VARCHAR2(50)                    NOT NULL,
   SEAT_NO              VARCHAR2(50),
   BANK_NO              VARCHAR2(50)                    NOT NULL,
   LOCAL_VALUE          VARCHAR2(100)                   NOT NULL,
   BANK_VALUE           VARCHAR2(100)                   NOT NULL,
   AUDIT_STATE          CHAR(1),
   AUDIT_NAME           VARCHAR2(100),
   AUDIT_ID             CHAR(24),
   AUDIT_TIME           DATE,
   MODIFY_NAME          VARCHAR2(100),
   ROW_VERSION          NUMBER(8,0)                     NOT NULL,
   CREATE_TIME          DATE                            NOT NULL,
   CREATE_ID            CHAR(24),
   CREATE_NAME          VARCHAR2(100),
   MODIFY_TIME          DATE                            NOT NULL,
   MODIFY_ID            CHAR(24),
   CONSTRAINT PK_T_FUND_TRADE_PARAM_CONVERT PRIMARY KEY (ID)
);

COMMENT ON TABLE T_FUND_TRADE_PARAM_CONVERT IS
'交易参数转换';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.ID IS
'PK';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.PARAM_TYPE IS
'参数类型，程序定义';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.PAY_SEAT_NO IS
'支付渠道代码';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.SEAT_NO IS
'席位号，保留';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.BANK_NO IS
'银行代码';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.LOCAL_VALUE IS
'本地值';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.BANK_VALUE IS
'银行值';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.AUDIT_STATE IS
'审核状态0未审核 1审核通过2审核不通过';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.AUDIT_NAME IS
'审核人名称';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.AUDIT_ID IS
'审核人ID';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.AUDIT_TIME IS
'审核时间';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.MODIFY_NAME IS
'修改人登录名称';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.ROW_VERSION IS
'版本';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.CREATE_ID IS
'创建人ID';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.CREATE_NAME IS
'创建人登录名称';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.MODIFY_TIME IS
'修改时间';

COMMENT ON COLUMN T_FUND_TRADE_PARAM_CONVERT.MODIFY_ID IS
'修改人ID';

/*==============================================================*/
/* View: V_FUND_FUND_CATEGORY_FUND                              */
/*==============================================================*/
CREATE OR REPLACE VIEW V_FUND_FUND_CATEGORY_FUND AS
SELECT T1.CATEGORY_ID,
    T1.FUND_CODE,
    T1.ORDER_FIELD,
    T2.CATEGORY_NAME,
    T3.FUND_NAME
  FROM T_FUND_FUND_CATAGORY_FUND_RELA T1
  INNER JOIN T_FUND_FUND_CATEGORY T2
  ON T2.ID = T1.CATEGORY_ID
  INNER JOIN T_FUND_FUND_INFO T3
  ON T3.FUND_CODE = T1.FUND_CODE
WITH READ ONLY;

 COMMENT ON TABLE V_FUND_FUND_CATEGORY_FUND IS
'基金分类基金视图';

