package topdeep.common.entity.db;

import common.entity.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemVisitLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public SystemVisitLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVisitSrcIsNull() {
            addCriterion("VISIT_SRC is null");
            return (Criteria) this;
        }

        public Criteria andVisitSrcIsNotNull() {
            addCriterion("VISIT_SRC is not null");
            return (Criteria) this;
        }

        public Criteria andVisitSrcEqualTo(String value) {
            addCriterion("VISIT_SRC =", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcNotEqualTo(String value) {
            addCriterion("VISIT_SRC <>", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcGreaterThan(String value) {
            addCriterion("VISIT_SRC >", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcGreaterThanOrEqualTo(String value) {
            addCriterion("VISIT_SRC >=", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcLessThan(String value) {
            addCriterion("VISIT_SRC <", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcLessThanOrEqualTo(String value) {
            addCriterion("VISIT_SRC <=", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcLike(String value) {
            addCriterion("VISIT_SRC like", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcNotLike(String value) {
            addCriterion("VISIT_SRC not like", value, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcIn(List<String> values) {
            addCriterion("VISIT_SRC in", values, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcNotIn(List<String> values) {
            addCriterion("VISIT_SRC not in", values, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcBetween(String value1, String value2) {
            addCriterion("VISIT_SRC between", value1, value2, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andVisitSrcNotBetween(String value1, String value2) {
            addCriterion("VISIT_SRC not between", value1, value2, "visitSrc");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("OPENID is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("OPENID is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("OPENID =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("OPENID <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("OPENID >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("OPENID >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("OPENID <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("OPENID <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("OPENID like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("OPENID not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("OPENID in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("OPENID not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("OPENID between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("OPENID not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("CHANNEL =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("CHANNEL <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("CHANNEL >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("CHANNEL <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("CHANNEL like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("CHANNEL not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("CHANNEL in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("CHANNEL not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("CHANNEL between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("CHANNEL not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andSrcVersionIsNull() {
            addCriterion("SRC_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andSrcVersionIsNotNull() {
            addCriterion("SRC_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andSrcVersionEqualTo(String value) {
            addCriterion("SRC_VERSION =", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionNotEqualTo(String value) {
            addCriterion("SRC_VERSION <>", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionGreaterThan(String value) {
            addCriterion("SRC_VERSION >", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_VERSION >=", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionLessThan(String value) {
            addCriterion("SRC_VERSION <", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionLessThanOrEqualTo(String value) {
            addCriterion("SRC_VERSION <=", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionLike(String value) {
            addCriterion("SRC_VERSION like", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionNotLike(String value) {
            addCriterion("SRC_VERSION not like", value, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionIn(List<String> values) {
            addCriterion("SRC_VERSION in", values, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionNotIn(List<String> values) {
            addCriterion("SRC_VERSION not in", values, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionBetween(String value1, String value2) {
            addCriterion("SRC_VERSION between", value1, value2, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andSrcVersionNotBetween(String value1, String value2) {
            addCriterion("SRC_VERSION not between", value1, value2, "srcVersion");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNull() {
            addCriterion("CLIENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNotNull() {
            addCriterion("CLIENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualTo(String value) {
            addCriterion("CLIENT_TYPE =", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotEqualTo(String value) {
            addCriterion("CLIENT_TYPE <>", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThan(String value) {
            addCriterion("CLIENT_TYPE >", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CLIENT_TYPE >=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThan(String value) {
            addCriterion("CLIENT_TYPE <", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThanOrEqualTo(String value) {
            addCriterion("CLIENT_TYPE <=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLike(String value) {
            addCriterion("CLIENT_TYPE like", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotLike(String value) {
            addCriterion("CLIENT_TYPE not like", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIn(List<String> values) {
            addCriterion("CLIENT_TYPE in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotIn(List<String> values) {
            addCriterion("CLIENT_TYPE not in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeBetween(String value1, String value2) {
            addCriterion("CLIENT_TYPE between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotBetween(String value1, String value2) {
            addCriterion("CLIENT_TYPE not between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andOsIsNull() {
            addCriterion("OS is null");
            return (Criteria) this;
        }

        public Criteria andOsIsNotNull() {
            addCriterion("OS is not null");
            return (Criteria) this;
        }

        public Criteria andOsEqualTo(String value) {
            addCriterion("OS =", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotEqualTo(String value) {
            addCriterion("OS <>", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThan(String value) {
            addCriterion("OS >", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThanOrEqualTo(String value) {
            addCriterion("OS >=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThan(String value) {
            addCriterion("OS <", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThanOrEqualTo(String value) {
            addCriterion("OS <=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLike(String value) {
            addCriterion("OS like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotLike(String value) {
            addCriterion("OS not like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsIn(List<String> values) {
            addCriterion("OS in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotIn(List<String> values) {
            addCriterion("OS not in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsBetween(String value1, String value2) {
            addCriterion("OS between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotBetween(String value1, String value2) {
            addCriterion("OS not between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNull() {
            addCriterion("OS_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNotNull() {
            addCriterion("OS_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andOsVersionEqualTo(String value) {
            addCriterion("OS_VERSION =", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotEqualTo(String value) {
            addCriterion("OS_VERSION <>", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThan(String value) {
            addCriterion("OS_VERSION >", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThanOrEqualTo(String value) {
            addCriterion("OS_VERSION >=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThan(String value) {
            addCriterion("OS_VERSION <", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThanOrEqualTo(String value) {
            addCriterion("OS_VERSION <=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLike(String value) {
            addCriterion("OS_VERSION like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotLike(String value) {
            addCriterion("OS_VERSION not like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionIn(List<String> values) {
            addCriterion("OS_VERSION in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotIn(List<String> values) {
            addCriterion("OS_VERSION not in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionBetween(String value1, String value2) {
            addCriterion("OS_VERSION between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotBetween(String value1, String value2) {
            addCriterion("OS_VERSION not between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andNetworkIsNull() {
            addCriterion("NETWORK is null");
            return (Criteria) this;
        }

        public Criteria andNetworkIsNotNull() {
            addCriterion("NETWORK is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkEqualTo(String value) {
            addCriterion("NETWORK =", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotEqualTo(String value) {
            addCriterion("NETWORK <>", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkGreaterThan(String value) {
            addCriterion("NETWORK >", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkGreaterThanOrEqualTo(String value) {
            addCriterion("NETWORK >=", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkLessThan(String value) {
            addCriterion("NETWORK <", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkLessThanOrEqualTo(String value) {
            addCriterion("NETWORK <=", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkLike(String value) {
            addCriterion("NETWORK like", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotLike(String value) {
            addCriterion("NETWORK not like", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkIn(List<String> values) {
            addCriterion("NETWORK in", values, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotIn(List<String> values) {
            addCriterion("NETWORK not in", values, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkBetween(String value1, String value2) {
            addCriterion("NETWORK between", value1, value2, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotBetween(String value1, String value2) {
            addCriterion("NETWORK not between", value1, value2, "network");
            return (Criteria) this;
        }

        public Criteria andServiceIsNull() {
            addCriterion("SERVICE is null");
            return (Criteria) this;
        }

        public Criteria andServiceIsNotNull() {
            addCriterion("SERVICE is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEqualTo(String value) {
            addCriterion("SERVICE =", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotEqualTo(String value) {
            addCriterion("SERVICE <>", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThan(String value) {
            addCriterion("SERVICE >", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICE >=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThan(String value) {
            addCriterion("SERVICE <", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThanOrEqualTo(String value) {
            addCriterion("SERVICE <=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLike(String value) {
            addCriterion("SERVICE like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotLike(String value) {
            addCriterion("SERVICE not like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceIn(List<String> values) {
            addCriterion("SERVICE in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotIn(List<String> values) {
            addCriterion("SERVICE not in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceBetween(String value1, String value2) {
            addCriterion("SERVICE between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotBetween(String value1, String value2) {
            addCriterion("SERVICE not between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("MOBILE_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("MOBILE_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("MOBILE_PHONE =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("MOBILE_PHONE >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("MOBILE_PHONE <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("MOBILE_PHONE like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("MOBILE_PHONE in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andScreenIsNull() {
            addCriterion("SCREEN is null");
            return (Criteria) this;
        }

        public Criteria andScreenIsNotNull() {
            addCriterion("SCREEN is not null");
            return (Criteria) this;
        }

        public Criteria andScreenEqualTo(String value) {
            addCriterion("SCREEN =", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenNotEqualTo(String value) {
            addCriterion("SCREEN <>", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenGreaterThan(String value) {
            addCriterion("SCREEN >", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenGreaterThanOrEqualTo(String value) {
            addCriterion("SCREEN >=", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenLessThan(String value) {
            addCriterion("SCREEN <", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenLessThanOrEqualTo(String value) {
            addCriterion("SCREEN <=", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenLike(String value) {
            addCriterion("SCREEN like", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenNotLike(String value) {
            addCriterion("SCREEN not like", value, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenIn(List<String> values) {
            addCriterion("SCREEN in", values, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenNotIn(List<String> values) {
            addCriterion("SCREEN not in", values, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenBetween(String value1, String value2) {
            addCriterion("SCREEN between", value1, value2, "screen");
            return (Criteria) this;
        }

        public Criteria andScreenNotBetween(String value1, String value2) {
            addCriterion("SCREEN not between", value1, value2, "screen");
            return (Criteria) this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("OTHER is null");
            return (Criteria) this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("OTHER is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("OTHER =", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("OTHER <>", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("OTHER >", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER >=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("OTHER <", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("OTHER <=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("OTHER like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("OTHER not like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherIn(List<String> values) {
            addCriterion("OTHER in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotIn(List<String> values) {
            addCriterion("OTHER not in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("OTHER between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("OTHER not between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdIsNull() {
            addCriterion("LOG_SESSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdIsNotNull() {
            addCriterion("LOG_SESSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdEqualTo(String value) {
            addCriterion("LOG_SESSION_ID =", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdNotEqualTo(String value) {
            addCriterion("LOG_SESSION_ID <>", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdGreaterThan(String value) {
            addCriterion("LOG_SESSION_ID >", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_SESSION_ID >=", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdLessThan(String value) {
            addCriterion("LOG_SESSION_ID <", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdLessThanOrEqualTo(String value) {
            addCriterion("LOG_SESSION_ID <=", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdLike(String value) {
            addCriterion("LOG_SESSION_ID like", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdNotLike(String value) {
            addCriterion("LOG_SESSION_ID not like", value, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdIn(List<String> values) {
            addCriterion("LOG_SESSION_ID in", values, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdNotIn(List<String> values) {
            addCriterion("LOG_SESSION_ID not in", values, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdBetween(String value1, String value2) {
            addCriterion("LOG_SESSION_ID between", value1, value2, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogSessionIdNotBetween(String value1, String value2) {
            addCriterion("LOG_SESSION_ID not between", value1, value2, "logSessionId");
            return (Criteria) this;
        }

        public Criteria andLogIpIsNull() {
            addCriterion("LOG_IP is null");
            return (Criteria) this;
        }

        public Criteria andLogIpIsNotNull() {
            addCriterion("LOG_IP is not null");
            return (Criteria) this;
        }

        public Criteria andLogIpEqualTo(String value) {
            addCriterion("LOG_IP =", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpNotEqualTo(String value) {
            addCriterion("LOG_IP <>", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpGreaterThan(String value) {
            addCriterion("LOG_IP >", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_IP >=", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpLessThan(String value) {
            addCriterion("LOG_IP <", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpLessThanOrEqualTo(String value) {
            addCriterion("LOG_IP <=", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpLike(String value) {
            addCriterion("LOG_IP like", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpNotLike(String value) {
            addCriterion("LOG_IP not like", value, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpIn(List<String> values) {
            addCriterion("LOG_IP in", values, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpNotIn(List<String> values) {
            addCriterion("LOG_IP not in", values, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpBetween(String value1, String value2) {
            addCriterion("LOG_IP between", value1, value2, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogIpNotBetween(String value1, String value2) {
            addCriterion("LOG_IP not between", value1, value2, "logIp");
            return (Criteria) this;
        }

        public Criteria andLogUaIsNull() {
            addCriterion("LOG_UA is null");
            return (Criteria) this;
        }

        public Criteria andLogUaIsNotNull() {
            addCriterion("LOG_UA is not null");
            return (Criteria) this;
        }

        public Criteria andLogUaEqualTo(String value) {
            addCriterion("LOG_UA =", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaNotEqualTo(String value) {
            addCriterion("LOG_UA <>", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaGreaterThan(String value) {
            addCriterion("LOG_UA >", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_UA >=", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaLessThan(String value) {
            addCriterion("LOG_UA <", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaLessThanOrEqualTo(String value) {
            addCriterion("LOG_UA <=", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaLike(String value) {
            addCriterion("LOG_UA like", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaNotLike(String value) {
            addCriterion("LOG_UA not like", value, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaIn(List<String> values) {
            addCriterion("LOG_UA in", values, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaNotIn(List<String> values) {
            addCriterion("LOG_UA not in", values, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaBetween(String value1, String value2) {
            addCriterion("LOG_UA between", value1, value2, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogUaNotBetween(String value1, String value2) {
            addCriterion("LOG_UA not between", value1, value2, "logUa");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlIsNull() {
            addCriterion("LOG_REFER_URL is null");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlIsNotNull() {
            addCriterion("LOG_REFER_URL is not null");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlEqualTo(String value) {
            addCriterion("LOG_REFER_URL =", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlNotEqualTo(String value) {
            addCriterion("LOG_REFER_URL <>", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlGreaterThan(String value) {
            addCriterion("LOG_REFER_URL >", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_REFER_URL >=", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlLessThan(String value) {
            addCriterion("LOG_REFER_URL <", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlLessThanOrEqualTo(String value) {
            addCriterion("LOG_REFER_URL <=", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlLike(String value) {
            addCriterion("LOG_REFER_URL like", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlNotLike(String value) {
            addCriterion("LOG_REFER_URL not like", value, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlIn(List<String> values) {
            addCriterion("LOG_REFER_URL in", values, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlNotIn(List<String> values) {
            addCriterion("LOG_REFER_URL not in", values, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlBetween(String value1, String value2) {
            addCriterion("LOG_REFER_URL between", value1, value2, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogReferUrlNotBetween(String value1, String value2) {
            addCriterion("LOG_REFER_URL not between", value1, value2, "logReferUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlIsNull() {
            addCriterion("LOG_URL is null");
            return (Criteria) this;
        }

        public Criteria andLogUrlIsNotNull() {
            addCriterion("LOG_URL is not null");
            return (Criteria) this;
        }

        public Criteria andLogUrlEqualTo(String value) {
            addCriterion("LOG_URL =", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlNotEqualTo(String value) {
            addCriterion("LOG_URL <>", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlGreaterThan(String value) {
            addCriterion("LOG_URL >", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_URL >=", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlLessThan(String value) {
            addCriterion("LOG_URL <", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlLessThanOrEqualTo(String value) {
            addCriterion("LOG_URL <=", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlLike(String value) {
            addCriterion("LOG_URL like", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlNotLike(String value) {
            addCriterion("LOG_URL not like", value, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlIn(List<String> values) {
            addCriterion("LOG_URL in", values, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlNotIn(List<String> values) {
            addCriterion("LOG_URL not in", values, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlBetween(String value1, String value2) {
            addCriterion("LOG_URL between", value1, value2, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogUrlNotBetween(String value1, String value2) {
            addCriterion("LOG_URL not between", value1, value2, "logUrl");
            return (Criteria) this;
        }

        public Criteria andLogParamIsNull() {
            addCriterion("LOG_PARAM is null");
            return (Criteria) this;
        }

        public Criteria andLogParamIsNotNull() {
            addCriterion("LOG_PARAM is not null");
            return (Criteria) this;
        }

        public Criteria andLogParamEqualTo(String value) {
            addCriterion("LOG_PARAM =", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamNotEqualTo(String value) {
            addCriterion("LOG_PARAM <>", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamGreaterThan(String value) {
            addCriterion("LOG_PARAM >", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_PARAM >=", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamLessThan(String value) {
            addCriterion("LOG_PARAM <", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamLessThanOrEqualTo(String value) {
            addCriterion("LOG_PARAM <=", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamLike(String value) {
            addCriterion("LOG_PARAM like", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamNotLike(String value) {
            addCriterion("LOG_PARAM not like", value, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamIn(List<String> values) {
            addCriterion("LOG_PARAM in", values, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamNotIn(List<String> values) {
            addCriterion("LOG_PARAM not in", values, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamBetween(String value1, String value2) {
            addCriterion("LOG_PARAM between", value1, value2, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogParamNotBetween(String value1, String value2) {
            addCriterion("LOG_PARAM not between", value1, value2, "logParam");
            return (Criteria) this;
        }

        public Criteria andLogTimeIsNull() {
            addCriterion("LOG_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLogTimeIsNotNull() {
            addCriterion("LOG_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLogTimeEqualTo(Date value) {
            addCriterion("LOG_TIME =", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotEqualTo(Date value) {
            addCriterion("LOG_TIME <>", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeGreaterThan(Date value) {
            addCriterion("LOG_TIME >", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LOG_TIME >=", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeLessThan(Date value) {
            addCriterion("LOG_TIME <", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeLessThanOrEqualTo(Date value) {
            addCriterion("LOG_TIME <=", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeIn(List<Date> values) {
            addCriterion("LOG_TIME in", values, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotIn(List<Date> values) {
            addCriterion("LOG_TIME not in", values, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeBetween(Date value1, Date value2) {
            addCriterion("LOG_TIME between", value1, value2, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotBetween(Date value1, Date value2) {
            addCriterion("LOG_TIME not between", value1, value2, "logTime");
            return (Criteria) this;
        }

        public Criteria andVisitResultIsNull() {
            addCriterion("VISIT_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andVisitResultIsNotNull() {
            addCriterion("VISIT_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andVisitResultEqualTo(String value) {
            addCriterion("VISIT_RESULT =", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultNotEqualTo(String value) {
            addCriterion("VISIT_RESULT <>", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultGreaterThan(String value) {
            addCriterion("VISIT_RESULT >", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultGreaterThanOrEqualTo(String value) {
            addCriterion("VISIT_RESULT >=", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultLessThan(String value) {
            addCriterion("VISIT_RESULT <", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultLessThanOrEqualTo(String value) {
            addCriterion("VISIT_RESULT <=", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultLike(String value) {
            addCriterion("VISIT_RESULT like", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultNotLike(String value) {
            addCriterion("VISIT_RESULT not like", value, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultIn(List<String> values) {
            addCriterion("VISIT_RESULT in", values, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultNotIn(List<String> values) {
            addCriterion("VISIT_RESULT not in", values, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultBetween(String value1, String value2) {
            addCriterion("VISIT_RESULT between", value1, value2, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitResultNotBetween(String value1, String value2) {
            addCriterion("VISIT_RESULT not between", value1, value2, "visitResult");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonIsNull() {
            addCriterion("VISIT_FAIL_REASON is null");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonIsNotNull() {
            addCriterion("VISIT_FAIL_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonEqualTo(String value) {
            addCriterion("VISIT_FAIL_REASON =", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonNotEqualTo(String value) {
            addCriterion("VISIT_FAIL_REASON <>", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonGreaterThan(String value) {
            addCriterion("VISIT_FAIL_REASON >", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonGreaterThanOrEqualTo(String value) {
            addCriterion("VISIT_FAIL_REASON >=", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonLessThan(String value) {
            addCriterion("VISIT_FAIL_REASON <", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonLessThanOrEqualTo(String value) {
            addCriterion("VISIT_FAIL_REASON <=", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonLike(String value) {
            addCriterion("VISIT_FAIL_REASON like", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonNotLike(String value) {
            addCriterion("VISIT_FAIL_REASON not like", value, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonIn(List<String> values) {
            addCriterion("VISIT_FAIL_REASON in", values, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonNotIn(List<String> values) {
            addCriterion("VISIT_FAIL_REASON not in", values, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonBetween(String value1, String value2) {
            addCriterion("VISIT_FAIL_REASON between", value1, value2, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitFailReasonNotBetween(String value1, String value2) {
            addCriterion("VISIT_FAIL_REASON not between", value1, value2, "visitFailReason");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewIsNull() {
            addCriterion("VISIT_RESULT_VIEW is null");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewIsNotNull() {
            addCriterion("VISIT_RESULT_VIEW is not null");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewEqualTo(String value) {
            addCriterion("VISIT_RESULT_VIEW =", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewNotEqualTo(String value) {
            addCriterion("VISIT_RESULT_VIEW <>", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewGreaterThan(String value) {
            addCriterion("VISIT_RESULT_VIEW >", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewGreaterThanOrEqualTo(String value) {
            addCriterion("VISIT_RESULT_VIEW >=", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewLessThan(String value) {
            addCriterion("VISIT_RESULT_VIEW <", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewLessThanOrEqualTo(String value) {
            addCriterion("VISIT_RESULT_VIEW <=", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewLike(String value) {
            addCriterion("VISIT_RESULT_VIEW like", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewNotLike(String value) {
            addCriterion("VISIT_RESULT_VIEW not like", value, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewIn(List<String> values) {
            addCriterion("VISIT_RESULT_VIEW in", values, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewNotIn(List<String> values) {
            addCriterion("VISIT_RESULT_VIEW not in", values, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewBetween(String value1, String value2) {
            addCriterion("VISIT_RESULT_VIEW between", value1, value2, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andVisitResultViewNotBetween(String value1, String value2) {
            addCriterion("VISIT_RESULT_VIEW not between", value1, value2, "visitResultView");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIsNull() {
            addCriterion("PROCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIsNotNull() {
            addCriterion("PROCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andProcessTimeEqualTo(Integer value) {
            addCriterion("PROCESS_TIME =", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotEqualTo(Integer value) {
            addCriterion("PROCESS_TIME <>", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeGreaterThan(Integer value) {
            addCriterion("PROCESS_TIME >", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROCESS_TIME >=", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeLessThan(Integer value) {
            addCriterion("PROCESS_TIME <", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeLessThanOrEqualTo(Integer value) {
            addCriterion("PROCESS_TIME <=", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIn(List<Integer> values) {
            addCriterion("PROCESS_TIME in", values, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotIn(List<Integer> values) {
            addCriterion("PROCESS_TIME not in", values, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeBetween(Integer value1, Integer value2) {
            addCriterion("PROCESS_TIME between", value1, value2, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("PROCESS_TIME not between", value1, value2, "processTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_visit_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_visit_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}