package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemClientActivation;
import topdeep.common.entity.db.SystemClientActivationExample;

public interface SystemClientActivationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int countByExample(SystemClientActivationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int deleteByExample(SystemClientActivationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int insert(SystemClientActivation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int insertSelective(SystemClientActivation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    List<SystemClientActivation> selectByExample(SystemClientActivationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    SystemClientActivation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemClientActivation record, @Param("example") SystemClientActivationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemClientActivation record, @Param("example") SystemClientActivationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemClientActivation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_activation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemClientActivation record);
}