package topdeep.common.entity.db;

import topdeep.common.entity.base.BaseEntity;

public class SystemWhiteListKey extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_white_list.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    private String systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_white_list.ID_TYPE
     *
     * @mbggenerated
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_white_list.ID_NO
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_white_list.FUNC_URL
     *
     * @mbggenerated
     */
    private String funcUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_white_list
     *
     * @mbggenerated
     */
    public SystemWhiteListKey(String systemType, String idType, String idNo, String funcUrl) {
        this.systemType = systemType;
        this.idType = idType;
        this.idNo = idNo;
        this.funcUrl = funcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_white_list
     *
     * @mbggenerated
     */
    public SystemWhiteListKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_white_list.SYSTEM_TYPE
     *
     * @return the value of t_system_white_list.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_white_list.SYSTEM_TYPE
     *
     * @param systemType the value for t_system_white_list.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_white_list.ID_TYPE
     *
     * @return the value of t_system_white_list.ID_TYPE
     *
     * @mbggenerated
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_white_list.ID_TYPE
     *
     * @param idType the value for t_system_white_list.ID_TYPE
     *
     * @mbggenerated
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_white_list.ID_NO
     *
     * @return the value of t_system_white_list.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_white_list.ID_NO
     *
     * @param idNo the value for t_system_white_list.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_white_list.FUNC_URL
     *
     * @return the value of t_system_white_list.FUNC_URL
     *
     * @mbggenerated
     */
    public String getFuncUrl() {
        return funcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_white_list.FUNC_URL
     *
     * @param funcUrl the value for t_system_white_list.FUNC_URL
     *
     * @mbggenerated
     */
    public void setFuncUrl(String funcUrl) {
        this.funcUrl = funcUrl == null ? null : funcUrl.trim();
    }
}