package topdeep.common.entity.db;

import java.util.Date;
import topdeep.common.entity.base.BaseEntity;

public class SystemAdmin extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LOGIN_EMAIL
     *
     * @mbggenerated
     */
    private String loginEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LOGIN_PASS_SALT
     *
     * @mbggenerated
     */
    private String loginPassSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LOGIN_PASS
     *
     * @mbggenerated
     */
    private String loginPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.MOBILE_TELEPHONE
     *
     * @mbggenerated
     */
    private String mobileTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.OTHER_TELEPHONE
     *
     * @mbggenerated
     */
    private String otherTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    private Date lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.LAST_LOGINADDRESS
     *
     * @mbggenerated
     */
    private String lastLoginaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.PARENT_ADMIN_ID
     *
     * @mbggenerated
     */
    private String parentAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.ROW_VERSION
     *
     * @mbggenerated
     */
    private Integer rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.CREATE_ID
     *
     * @mbggenerated
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.CREATE_NAME
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.MODIFY_NAME
     *
     * @mbggenerated
     */
    private String modifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.AUDIT_TIME
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.AUDIT_ID
     *
     * @mbggenerated
     */
    private String auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.AUDIT_NAME
     *
     * @mbggenerated
     */
    private String auditName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.AUDIT_STATE
     *
     * @mbggenerated
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_admin.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin
     *
     * @mbggenerated
     */
    public SystemAdmin(String id, String name, String state, String loginEmail, String loginName, String loginPassSalt, String loginPass, String mobileTelephone, String otherTelephone, Date lastLogintime, String lastLoginaddress, String memo, String parentAdminId, Integer rowVersion, Date createTime, String createId, String createName, Date modifyTime, String modifyId, String modifyName, Date auditTime, String auditId, String auditName, String auditState, String deleted) {
        this.id = id;
        this.name = name;
        this.state = state;
        this.loginEmail = loginEmail;
        this.loginName = loginName;
        this.loginPassSalt = loginPassSalt;
        this.loginPass = loginPass;
        this.mobileTelephone = mobileTelephone;
        this.otherTelephone = otherTelephone;
        this.lastLogintime = lastLogintime;
        this.lastLoginaddress = lastLoginaddress;
        this.memo = memo;
        this.parentAdminId = parentAdminId;
        this.rowVersion = rowVersion;
        this.createTime = createTime;
        this.createId = createId;
        this.createName = createName;
        this.modifyTime = modifyTime;
        this.modifyId = modifyId;
        this.modifyName = modifyName;
        this.auditTime = auditTime;
        this.auditId = auditId;
        this.auditName = auditName;
        this.auditState = auditState;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin
     *
     * @mbggenerated
     */
    public SystemAdmin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.ID
     *
     * @return the value of t_system_admin.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.ID
     *
     * @param id the value for t_system_admin.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.NAME
     *
     * @return the value of t_system_admin.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.NAME
     *
     * @param name the value for t_system_admin.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.STATE
     *
     * @return the value of t_system_admin.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.STATE
     *
     * @param state the value for t_system_admin.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LOGIN_EMAIL
     *
     * @return the value of t_system_admin.LOGIN_EMAIL
     *
     * @mbggenerated
     */
    public String getLoginEmail() {
        return loginEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LOGIN_EMAIL
     *
     * @param loginEmail the value for t_system_admin.LOGIN_EMAIL
     *
     * @mbggenerated
     */
    public void setLoginEmail(String loginEmail) {
        this.loginEmail = loginEmail == null ? null : loginEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LOGIN_NAME
     *
     * @return the value of t_system_admin.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LOGIN_NAME
     *
     * @param loginName the value for t_system_admin.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LOGIN_PASS_SALT
     *
     * @return the value of t_system_admin.LOGIN_PASS_SALT
     *
     * @mbggenerated
     */
    public String getLoginPassSalt() {
        return loginPassSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LOGIN_PASS_SALT
     *
     * @param loginPassSalt the value for t_system_admin.LOGIN_PASS_SALT
     *
     * @mbggenerated
     */
    public void setLoginPassSalt(String loginPassSalt) {
        this.loginPassSalt = loginPassSalt == null ? null : loginPassSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LOGIN_PASS
     *
     * @return the value of t_system_admin.LOGIN_PASS
     *
     * @mbggenerated
     */
    public String getLoginPass() {
        return loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LOGIN_PASS
     *
     * @param loginPass the value for t_system_admin.LOGIN_PASS
     *
     * @mbggenerated
     */
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass == null ? null : loginPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.MOBILE_TELEPHONE
     *
     * @return the value of t_system_admin.MOBILE_TELEPHONE
     *
     * @mbggenerated
     */
    public String getMobileTelephone() {
        return mobileTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.MOBILE_TELEPHONE
     *
     * @param mobileTelephone the value for t_system_admin.MOBILE_TELEPHONE
     *
     * @mbggenerated
     */
    public void setMobileTelephone(String mobileTelephone) {
        this.mobileTelephone = mobileTelephone == null ? null : mobileTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.OTHER_TELEPHONE
     *
     * @return the value of t_system_admin.OTHER_TELEPHONE
     *
     * @mbggenerated
     */
    public String getOtherTelephone() {
        return otherTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.OTHER_TELEPHONE
     *
     * @param otherTelephone the value for t_system_admin.OTHER_TELEPHONE
     *
     * @mbggenerated
     */
    public void setOtherTelephone(String otherTelephone) {
        this.otherTelephone = otherTelephone == null ? null : otherTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LAST_LOGINTIME
     *
     * @return the value of t_system_admin.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LAST_LOGINTIME
     *
     * @param lastLogintime the value for t_system_admin.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.LAST_LOGINADDRESS
     *
     * @return the value of t_system_admin.LAST_LOGINADDRESS
     *
     * @mbggenerated
     */
    public String getLastLoginaddress() {
        return lastLoginaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.LAST_LOGINADDRESS
     *
     * @param lastLoginaddress the value for t_system_admin.LAST_LOGINADDRESS
     *
     * @mbggenerated
     */
    public void setLastLoginaddress(String lastLoginaddress) {
        this.lastLoginaddress = lastLoginaddress == null ? null : lastLoginaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.MEMO
     *
     * @return the value of t_system_admin.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.MEMO
     *
     * @param memo the value for t_system_admin.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.PARENT_ADMIN_ID
     *
     * @return the value of t_system_admin.PARENT_ADMIN_ID
     *
     * @mbggenerated
     */
    public String getParentAdminId() {
        return parentAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.PARENT_ADMIN_ID
     *
     * @param parentAdminId the value for t_system_admin.PARENT_ADMIN_ID
     *
     * @mbggenerated
     */
    public void setParentAdminId(String parentAdminId) {
        this.parentAdminId = parentAdminId == null ? null : parentAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.ROW_VERSION
     *
     * @return the value of t_system_admin.ROW_VERSION
     *
     * @mbggenerated
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.ROW_VERSION
     *
     * @param rowVersion the value for t_system_admin.ROW_VERSION
     *
     * @mbggenerated
     */
    public void setRowVersion(Integer rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.CREATE_TIME
     *
     * @return the value of t_system_admin.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.CREATE_TIME
     *
     * @param createTime the value for t_system_admin.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.CREATE_ID
     *
     * @return the value of t_system_admin.CREATE_ID
     *
     * @mbggenerated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.CREATE_ID
     *
     * @param createId the value for t_system_admin.CREATE_ID
     *
     * @mbggenerated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.CREATE_NAME
     *
     * @return the value of t_system_admin.CREATE_NAME
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.CREATE_NAME
     *
     * @param createName the value for t_system_admin.CREATE_NAME
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.MODIFY_TIME
     *
     * @return the value of t_system_admin.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.MODIFY_TIME
     *
     * @param modifyTime the value for t_system_admin.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.MODIFY_ID
     *
     * @return the value of t_system_admin.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.MODIFY_ID
     *
     * @param modifyId the value for t_system_admin.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.MODIFY_NAME
     *
     * @return the value of t_system_admin.MODIFY_NAME
     *
     * @mbggenerated
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.MODIFY_NAME
     *
     * @param modifyName the value for t_system_admin.MODIFY_NAME
     *
     * @mbggenerated
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.AUDIT_TIME
     *
     * @return the value of t_system_admin.AUDIT_TIME
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.AUDIT_TIME
     *
     * @param auditTime the value for t_system_admin.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.AUDIT_ID
     *
     * @return the value of t_system_admin.AUDIT_ID
     *
     * @mbggenerated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.AUDIT_ID
     *
     * @param auditId the value for t_system_admin.AUDIT_ID
     *
     * @mbggenerated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId == null ? null : auditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.AUDIT_NAME
     *
     * @return the value of t_system_admin.AUDIT_NAME
     *
     * @mbggenerated
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.AUDIT_NAME
     *
     * @param auditName the value for t_system_admin.AUDIT_NAME
     *
     * @mbggenerated
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.AUDIT_STATE
     *
     * @return the value of t_system_admin.AUDIT_STATE
     *
     * @mbggenerated
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.AUDIT_STATE
     *
     * @param auditState the value for t_system_admin.AUDIT_STATE
     *
     * @mbggenerated
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_admin.DELETED
     *
     * @return the value of t_system_admin.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_admin.DELETED
     *
     * @param deleted the value for t_system_admin.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}