package topdeep.common.entity.db;

import common.entity.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemCronJobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public SystemCronJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("OWNER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("OWNER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(String value) {
            addCriterion("OWNER_ID =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(String value) {
            addCriterion("OWNER_ID <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(String value) {
            addCriterion("OWNER_ID >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER_ID >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(String value) {
            addCriterion("OWNER_ID <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(String value) {
            addCriterion("OWNER_ID <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLike(String value) {
            addCriterion("OWNER_ID like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotLike(String value) {
            addCriterion("OWNER_ID not like", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<String> values) {
            addCriterion("OWNER_ID in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<String> values) {
            addCriterion("OWNER_ID not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(String value1, String value2) {
            addCriterion("OWNER_ID between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(String value1, String value2) {
            addCriterion("OWNER_ID not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNull() {
            addCriterion("JOB_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andJobTypeIsNotNull() {
            addCriterion("JOB_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andJobTypeEqualTo(String value) {
            addCriterion("JOB_TYPE =", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotEqualTo(String value) {
            addCriterion("JOB_TYPE <>", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThan(String value) {
            addCriterion("JOB_TYPE >", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_TYPE >=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThan(String value) {
            addCriterion("JOB_TYPE <", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLessThanOrEqualTo(String value) {
            addCriterion("JOB_TYPE <=", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeLike(String value) {
            addCriterion("JOB_TYPE like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotLike(String value) {
            addCriterion("JOB_TYPE not like", value, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeIn(List<String> values) {
            addCriterion("JOB_TYPE in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotIn(List<String> values) {
            addCriterion("JOB_TYPE not in", values, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeBetween(String value1, String value2) {
            addCriterion("JOB_TYPE between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobTypeNotBetween(String value1, String value2) {
            addCriterion("JOB_TYPE not between", value1, value2, "jobType");
            return (Criteria) this;
        }

        public Criteria andJobFromIsNull() {
            addCriterion("JOB_FROM is null");
            return (Criteria) this;
        }

        public Criteria andJobFromIsNotNull() {
            addCriterion("JOB_FROM is not null");
            return (Criteria) this;
        }

        public Criteria andJobFromEqualTo(String value) {
            addCriterion("JOB_FROM =", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromNotEqualTo(String value) {
            addCriterion("JOB_FROM <>", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromGreaterThan(String value) {
            addCriterion("JOB_FROM >", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_FROM >=", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromLessThan(String value) {
            addCriterion("JOB_FROM <", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromLessThanOrEqualTo(String value) {
            addCriterion("JOB_FROM <=", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromLike(String value) {
            addCriterion("JOB_FROM like", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromNotLike(String value) {
            addCriterion("JOB_FROM not like", value, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromIn(List<String> values) {
            addCriterion("JOB_FROM in", values, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromNotIn(List<String> values) {
            addCriterion("JOB_FROM not in", values, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromBetween(String value1, String value2) {
            addCriterion("JOB_FROM between", value1, value2, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobFromNotBetween(String value1, String value2) {
            addCriterion("JOB_FROM not between", value1, value2, "jobFrom");
            return (Criteria) this;
        }

        public Criteria andJobLocateIsNull() {
            addCriterion("JOB_LOCATE is null");
            return (Criteria) this;
        }

        public Criteria andJobLocateIsNotNull() {
            addCriterion("JOB_LOCATE is not null");
            return (Criteria) this;
        }

        public Criteria andJobLocateEqualTo(String value) {
            addCriterion("JOB_LOCATE =", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateNotEqualTo(String value) {
            addCriterion("JOB_LOCATE <>", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateGreaterThan(String value) {
            addCriterion("JOB_LOCATE >", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_LOCATE >=", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateLessThan(String value) {
            addCriterion("JOB_LOCATE <", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateLessThanOrEqualTo(String value) {
            addCriterion("JOB_LOCATE <=", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateLike(String value) {
            addCriterion("JOB_LOCATE like", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateNotLike(String value) {
            addCriterion("JOB_LOCATE not like", value, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateIn(List<String> values) {
            addCriterion("JOB_LOCATE in", values, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateNotIn(List<String> values) {
            addCriterion("JOB_LOCATE not in", values, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateBetween(String value1, String value2) {
            addCriterion("JOB_LOCATE between", value1, value2, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobLocateNotBetween(String value1, String value2) {
            addCriterion("JOB_LOCATE not between", value1, value2, "jobLocate");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdIsNull() {
            addCriterion("JOB_BEAN_ID is null");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdIsNotNull() {
            addCriterion("JOB_BEAN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdEqualTo(String value) {
            addCriterion("JOB_BEAN_ID =", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdNotEqualTo(String value) {
            addCriterion("JOB_BEAN_ID <>", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdGreaterThan(String value) {
            addCriterion("JOB_BEAN_ID >", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_BEAN_ID >=", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdLessThan(String value) {
            addCriterion("JOB_BEAN_ID <", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdLessThanOrEqualTo(String value) {
            addCriterion("JOB_BEAN_ID <=", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdLike(String value) {
            addCriterion("JOB_BEAN_ID like", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdNotLike(String value) {
            addCriterion("JOB_BEAN_ID not like", value, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdIn(List<String> values) {
            addCriterion("JOB_BEAN_ID in", values, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdNotIn(List<String> values) {
            addCriterion("JOB_BEAN_ID not in", values, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdBetween(String value1, String value2) {
            addCriterion("JOB_BEAN_ID between", value1, value2, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobBeanIdNotBetween(String value1, String value2) {
            addCriterion("JOB_BEAN_ID not between", value1, value2, "jobBeanId");
            return (Criteria) this;
        }

        public Criteria andJobVersionIsNull() {
            addCriterion("JOB_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andJobVersionIsNotNull() {
            addCriterion("JOB_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andJobVersionEqualTo(Integer value) {
            addCriterion("JOB_VERSION =", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionNotEqualTo(Integer value) {
            addCriterion("JOB_VERSION <>", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionGreaterThan(Integer value) {
            addCriterion("JOB_VERSION >", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("JOB_VERSION >=", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionLessThan(Integer value) {
            addCriterion("JOB_VERSION <", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionLessThanOrEqualTo(Integer value) {
            addCriterion("JOB_VERSION <=", value, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionIn(List<Integer> values) {
            addCriterion("JOB_VERSION in", values, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionNotIn(List<Integer> values) {
            addCriterion("JOB_VERSION not in", values, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionBetween(Integer value1, Integer value2) {
            addCriterion("JOB_VERSION between", value1, value2, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andJobVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("JOB_VERSION not between", value1, value2, "jobVersion");
            return (Criteria) this;
        }

        public Criteria andCycleValueIsNull() {
            addCriterion("CYCLE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andCycleValueIsNotNull() {
            addCriterion("CYCLE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andCycleValueEqualTo(Integer value) {
            addCriterion("CYCLE_VALUE =", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueNotEqualTo(Integer value) {
            addCriterion("CYCLE_VALUE <>", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueGreaterThan(Integer value) {
            addCriterion("CYCLE_VALUE >", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("CYCLE_VALUE >=", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueLessThan(Integer value) {
            addCriterion("CYCLE_VALUE <", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueLessThanOrEqualTo(Integer value) {
            addCriterion("CYCLE_VALUE <=", value, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueIn(List<Integer> values) {
            addCriterion("CYCLE_VALUE in", values, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueNotIn(List<Integer> values) {
            addCriterion("CYCLE_VALUE not in", values, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueBetween(Integer value1, Integer value2) {
            addCriterion("CYCLE_VALUE between", value1, value2, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleValueNotBetween(Integer value1, Integer value2) {
            addCriterion("CYCLE_VALUE not between", value1, value2, "cycleValue");
            return (Criteria) this;
        }

        public Criteria andCycleUnitIsNull() {
            addCriterion("CYCLE_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andCycleUnitIsNotNull() {
            addCriterion("CYCLE_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andCycleUnitEqualTo(String value) {
            addCriterion("CYCLE_UNIT =", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitNotEqualTo(String value) {
            addCriterion("CYCLE_UNIT <>", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitGreaterThan(String value) {
            addCriterion("CYCLE_UNIT >", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitGreaterThanOrEqualTo(String value) {
            addCriterion("CYCLE_UNIT >=", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitLessThan(String value) {
            addCriterion("CYCLE_UNIT <", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitLessThanOrEqualTo(String value) {
            addCriterion("CYCLE_UNIT <=", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitLike(String value) {
            addCriterion("CYCLE_UNIT like", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitNotLike(String value) {
            addCriterion("CYCLE_UNIT not like", value, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitIn(List<String> values) {
            addCriterion("CYCLE_UNIT in", values, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitNotIn(List<String> values) {
            addCriterion("CYCLE_UNIT not in", values, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitBetween(String value1, String value2) {
            addCriterion("CYCLE_UNIT between", value1, value2, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andCycleUnitNotBetween(String value1, String value2) {
            addCriterion("CYCLE_UNIT not between", value1, value2, "cycleUnit");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeIsNull() {
            addCriterion("LAST_SUCCESS_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeIsNotNull() {
            addCriterion("LAST_SUCCESS_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeEqualTo(Date value) {
            addCriterion("LAST_SUCCESS_TIME =", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeNotEqualTo(Date value) {
            addCriterion("LAST_SUCCESS_TIME <>", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeGreaterThan(Date value) {
            addCriterion("LAST_SUCCESS_TIME >", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_SUCCESS_TIME >=", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeLessThan(Date value) {
            addCriterion("LAST_SUCCESS_TIME <", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_SUCCESS_TIME <=", value, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeIn(List<Date> values) {
            addCriterion("LAST_SUCCESS_TIME in", values, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeNotIn(List<Date> values) {
            addCriterion("LAST_SUCCESS_TIME not in", values, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_SUCCESS_TIME between", value1, value2, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andLastSuccessTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_SUCCESS_TIME not between", value1, value2, "lastSuccessTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeIsNull() {
            addCriterion("FIRST_EXECUTE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeIsNotNull() {
            addCriterion("FIRST_EXECUTE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeEqualTo(Date value) {
            addCriterion("FIRST_EXECUTE_TIME =", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeNotEqualTo(Date value) {
            addCriterion("FIRST_EXECUTE_TIME <>", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeGreaterThan(Date value) {
            addCriterion("FIRST_EXECUTE_TIME >", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FIRST_EXECUTE_TIME >=", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeLessThan(Date value) {
            addCriterion("FIRST_EXECUTE_TIME <", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeLessThanOrEqualTo(Date value) {
            addCriterion("FIRST_EXECUTE_TIME <=", value, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeIn(List<Date> values) {
            addCriterion("FIRST_EXECUTE_TIME in", values, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeNotIn(List<Date> values) {
            addCriterion("FIRST_EXECUTE_TIME not in", values, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeBetween(Date value1, Date value2) {
            addCriterion("FIRST_EXECUTE_TIME between", value1, value2, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andFirstExecuteTimeNotBetween(Date value1, Date value2) {
            addCriterion("FIRST_EXECUTE_TIME not between", value1, value2, "firstExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeIsNull() {
            addCriterion("NEXT_EXECUTE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeIsNotNull() {
            addCriterion("NEXT_EXECUTE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeEqualTo(Date value) {
            addCriterion("NEXT_EXECUTE_TIME =", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeNotEqualTo(Date value) {
            addCriterion("NEXT_EXECUTE_TIME <>", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeGreaterThan(Date value) {
            addCriterion("NEXT_EXECUTE_TIME >", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("NEXT_EXECUTE_TIME >=", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeLessThan(Date value) {
            addCriterion("NEXT_EXECUTE_TIME <", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeLessThanOrEqualTo(Date value) {
            addCriterion("NEXT_EXECUTE_TIME <=", value, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeIn(List<Date> values) {
            addCriterion("NEXT_EXECUTE_TIME in", values, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeNotIn(List<Date> values) {
            addCriterion("NEXT_EXECUTE_TIME not in", values, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeBetween(Date value1, Date value2) {
            addCriterion("NEXT_EXECUTE_TIME between", value1, value2, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andNextExecuteTimeNotBetween(Date value1, Date value2) {
            addCriterion("NEXT_EXECUTE_TIME not between", value1, value2, "nextExecuteTime");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIsNull() {
            addCriterion("SUCCESS_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIsNotNull() {
            addCriterion("SUCCESS_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessCountEqualTo(Integer value) {
            addCriterion("SUCCESS_COUNT =", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotEqualTo(Integer value) {
            addCriterion("SUCCESS_COUNT <>", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountGreaterThan(Integer value) {
            addCriterion("SUCCESS_COUNT >", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUCCESS_COUNT >=", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountLessThan(Integer value) {
            addCriterion("SUCCESS_COUNT <", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountLessThanOrEqualTo(Integer value) {
            addCriterion("SUCCESS_COUNT <=", value, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountIn(List<Integer> values) {
            addCriterion("SUCCESS_COUNT in", values, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotIn(List<Integer> values) {
            addCriterion("SUCCESS_COUNT not in", values, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountBetween(Integer value1, Integer value2) {
            addCriterion("SUCCESS_COUNT between", value1, value2, "successCount");
            return (Criteria) this;
        }

        public Criteria andSuccessCountNotBetween(Integer value1, Integer value2) {
            addCriterion("SUCCESS_COUNT not between", value1, value2, "successCount");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNull() {
            addCriterion("FAIL_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNotNull() {
            addCriterion("FAIL_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andFailCountEqualTo(Integer value) {
            addCriterion("FAIL_COUNT =", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotEqualTo(Integer value) {
            addCriterion("FAIL_COUNT <>", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThan(Integer value) {
            addCriterion("FAIL_COUNT >", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAIL_COUNT >=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThan(Integer value) {
            addCriterion("FAIL_COUNT <", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThanOrEqualTo(Integer value) {
            addCriterion("FAIL_COUNT <=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountIn(List<Integer> values) {
            addCriterion("FAIL_COUNT in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotIn(List<Integer> values) {
            addCriterion("FAIL_COUNT not in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountBetween(Integer value1, Integer value2) {
            addCriterion("FAIL_COUNT between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotBetween(Integer value1, Integer value2) {
            addCriterion("FAIL_COUNT not between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNull() {
            addCriterion("TOTAL_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNotNull() {
            addCriterion("TOTAL_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountEqualTo(Integer value) {
            addCriterion("TOTAL_COUNT =", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotEqualTo(Integer value) {
            addCriterion("TOTAL_COUNT <>", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThan(Integer value) {
            addCriterion("TOTAL_COUNT >", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_COUNT >=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThan(Integer value) {
            addCriterion("TOTAL_COUNT <", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_COUNT <=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIn(List<Integer> values) {
            addCriterion("TOTAL_COUNT in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotIn(List<Integer> values) {
            addCriterion("TOTAL_COUNT not in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_COUNT between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_COUNT not between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultIsNull() {
            addCriterion("LAST_EXECUTE_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultIsNotNull() {
            addCriterion("LAST_EXECUTE_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultEqualTo(String value) {
            addCriterion("LAST_EXECUTE_RESULT =", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultNotEqualTo(String value) {
            addCriterion("LAST_EXECUTE_RESULT <>", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultGreaterThan(String value) {
            addCriterion("LAST_EXECUTE_RESULT >", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_EXECUTE_RESULT >=", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultLessThan(String value) {
            addCriterion("LAST_EXECUTE_RESULT <", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultLessThanOrEqualTo(String value) {
            addCriterion("LAST_EXECUTE_RESULT <=", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultLike(String value) {
            addCriterion("LAST_EXECUTE_RESULT like", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultNotLike(String value) {
            addCriterion("LAST_EXECUTE_RESULT not like", value, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultIn(List<String> values) {
            addCriterion("LAST_EXECUTE_RESULT in", values, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultNotIn(List<String> values) {
            addCriterion("LAST_EXECUTE_RESULT not in", values, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultBetween(String value1, String value2) {
            addCriterion("LAST_EXECUTE_RESULT between", value1, value2, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteResultNotBetween(String value1, String value2) {
            addCriterion("LAST_EXECUTE_RESULT not between", value1, value2, "lastExecuteResult");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageIsNull() {
            addCriterion("LAST_EXECUTE_MESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageIsNotNull() {
            addCriterion("LAST_EXECUTE_MESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageEqualTo(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE =", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageNotEqualTo(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE <>", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageGreaterThan(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE >", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE >=", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageLessThan(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE <", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageLessThanOrEqualTo(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE <=", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageLike(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE like", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageNotLike(String value) {
            addCriterion("LAST_EXECUTE_MESSAGE not like", value, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageIn(List<String> values) {
            addCriterion("LAST_EXECUTE_MESSAGE in", values, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageNotIn(List<String> values) {
            addCriterion("LAST_EXECUTE_MESSAGE not in", values, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageBetween(String value1, String value2) {
            addCriterion("LAST_EXECUTE_MESSAGE between", value1, value2, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andLastExecuteMessageNotBetween(String value1, String value2) {
            addCriterion("LAST_EXECUTE_MESSAGE not between", value1, value2, "lastExecuteMessage");
            return (Criteria) this;
        }

        public Criteria andJobStateIsNull() {
            addCriterion("JOB_STATE is null");
            return (Criteria) this;
        }

        public Criteria andJobStateIsNotNull() {
            addCriterion("JOB_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andJobStateEqualTo(String value) {
            addCriterion("JOB_STATE =", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotEqualTo(String value) {
            addCriterion("JOB_STATE <>", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateGreaterThan(String value) {
            addCriterion("JOB_STATE >", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_STATE >=", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLessThan(String value) {
            addCriterion("JOB_STATE <", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLessThanOrEqualTo(String value) {
            addCriterion("JOB_STATE <=", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateLike(String value) {
            addCriterion("JOB_STATE like", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotLike(String value) {
            addCriterion("JOB_STATE not like", value, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateIn(List<String> values) {
            addCriterion("JOB_STATE in", values, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotIn(List<String> values) {
            addCriterion("JOB_STATE not in", values, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateBetween(String value1, String value2) {
            addCriterion("JOB_STATE between", value1, value2, "jobState");
            return (Criteria) this;
        }

        public Criteria andJobStateNotBetween(String value1, String value2) {
            addCriterion("JOB_STATE not between", value1, value2, "jobState");
            return (Criteria) this;
        }

        public Criteria andLogEnabledIsNull() {
            addCriterion("LOG_ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andLogEnabledIsNotNull() {
            addCriterion("LOG_ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andLogEnabledEqualTo(String value) {
            addCriterion("LOG_ENABLED =", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledNotEqualTo(String value) {
            addCriterion("LOG_ENABLED <>", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledGreaterThan(String value) {
            addCriterion("LOG_ENABLED >", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_ENABLED >=", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledLessThan(String value) {
            addCriterion("LOG_ENABLED <", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledLessThanOrEqualTo(String value) {
            addCriterion("LOG_ENABLED <=", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledLike(String value) {
            addCriterion("LOG_ENABLED like", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledNotLike(String value) {
            addCriterion("LOG_ENABLED not like", value, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledIn(List<String> values) {
            addCriterion("LOG_ENABLED in", values, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledNotIn(List<String> values) {
            addCriterion("LOG_ENABLED not in", values, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledBetween(String value1, String value2) {
            addCriterion("LOG_ENABLED between", value1, value2, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andLogEnabledNotBetween(String value1, String value2) {
            addCriterion("LOG_ENABLED not between", value1, value2, "logEnabled");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerIsNull() {
            addCriterion("CURRENT_EXEC_SERVER is null");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerIsNotNull() {
            addCriterion("CURRENT_EXEC_SERVER is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerEqualTo(String value) {
            addCriterion("CURRENT_EXEC_SERVER =", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerNotEqualTo(String value) {
            addCriterion("CURRENT_EXEC_SERVER <>", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerGreaterThan(String value) {
            addCriterion("CURRENT_EXEC_SERVER >", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_EXEC_SERVER >=", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerLessThan(String value) {
            addCriterion("CURRENT_EXEC_SERVER <", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_EXEC_SERVER <=", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerLike(String value) {
            addCriterion("CURRENT_EXEC_SERVER like", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerNotLike(String value) {
            addCriterion("CURRENT_EXEC_SERVER not like", value, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerIn(List<String> values) {
            addCriterion("CURRENT_EXEC_SERVER in", values, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerNotIn(List<String> values) {
            addCriterion("CURRENT_EXEC_SERVER not in", values, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerBetween(String value1, String value2) {
            addCriterion("CURRENT_EXEC_SERVER between", value1, value2, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andCurrentExecServerNotBetween(String value1, String value2) {
            addCriterion("CURRENT_EXEC_SERVER not between", value1, value2, "currentExecServer");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("ROW_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("ROW_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Integer value) {
            addCriterion("ROW_VERSION =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Integer value) {
            addCriterion("ROW_VERSION <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Integer value) {
            addCriterion("ROW_VERSION >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROW_VERSION >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Integer value) {
            addCriterion("ROW_VERSION <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Integer value) {
            addCriterion("ROW_VERSION <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Integer> values) {
            addCriterion("ROW_VERSION in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Integer> values) {
            addCriterion("ROW_VERSION not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Integer value1, Integer value2) {
            addCriterion("ROW_VERSION between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("ROW_VERSION not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("CREATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("CREATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(String value) {
            addCriterion("CREATE_ID =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(String value) {
            addCriterion("CREATE_ID <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(String value) {
            addCriterion("CREATE_ID >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_ID >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(String value) {
            addCriterion("CREATE_ID <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_ID <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLike(String value) {
            addCriterion("CREATE_ID like", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotLike(String value) {
            addCriterion("CREATE_ID not like", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<String> values) {
            addCriterion("CREATE_ID in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<String> values) {
            addCriterion("CREATE_ID not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(String value1, String value2) {
            addCriterion("CREATE_ID between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_ID not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("CREATE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("CREATE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("CREATE_NAME =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("CREATE_NAME <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("CREATE_NAME >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("CREATE_NAME <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("CREATE_NAME like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("CREATE_NAME not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("CREATE_NAME in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("CREATE_NAME not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("CREATE_NAME between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("CREATE_NAME not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("MODIFY_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("MODIFY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(String value) {
            addCriterion("MODIFY_ID =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(String value) {
            addCriterion("MODIFY_ID <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(String value) {
            addCriterion("MODIFY_ID >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_ID >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(String value) {
            addCriterion("MODIFY_ID <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_ID <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLike(String value) {
            addCriterion("MODIFY_ID like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotLike(String value) {
            addCriterion("MODIFY_ID not like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<String> values) {
            addCriterion("MODIFY_ID in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<String> values) {
            addCriterion("MODIFY_ID not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(String value1, String value2) {
            addCriterion("MODIFY_ID between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(String value1, String value2) {
            addCriterion("MODIFY_ID not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyNameIsNull() {
            addCriterion("MODIFY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andModifyNameIsNotNull() {
            addCriterion("MODIFY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyNameEqualTo(String value) {
            addCriterion("MODIFY_NAME =", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameNotEqualTo(String value) {
            addCriterion("MODIFY_NAME <>", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameGreaterThan(String value) {
            addCriterion("MODIFY_NAME >", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_NAME >=", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameLessThan(String value) {
            addCriterion("MODIFY_NAME <", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_NAME <=", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameLike(String value) {
            addCriterion("MODIFY_NAME like", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameNotLike(String value) {
            addCriterion("MODIFY_NAME not like", value, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameIn(List<String> values) {
            addCriterion("MODIFY_NAME in", values, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameNotIn(List<String> values) {
            addCriterion("MODIFY_NAME not in", values, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameBetween(String value1, String value2) {
            addCriterion("MODIFY_NAME between", value1, value2, "modifyName");
            return (Criteria) this;
        }

        public Criteria andModifyNameNotBetween(String value1, String value2) {
            addCriterion("MODIFY_NAME not between", value1, value2, "modifyName");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("AUDIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("AUDIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("AUDIT_TIME =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("AUDIT_TIME <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("AUDIT_TIME >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AUDIT_TIME >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("AUDIT_TIME <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("AUDIT_TIME <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("AUDIT_TIME in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("AUDIT_TIME not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("AUDIT_TIME between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("AUDIT_TIME not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditIdIsNull() {
            addCriterion("AUDIT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAuditIdIsNotNull() {
            addCriterion("AUDIT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAuditIdEqualTo(String value) {
            addCriterion("AUDIT_ID =", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotEqualTo(String value) {
            addCriterion("AUDIT_ID <>", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThan(String value) {
            addCriterion("AUDIT_ID >", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdGreaterThanOrEqualTo(String value) {
            addCriterion("AUDIT_ID >=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThan(String value) {
            addCriterion("AUDIT_ID <", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLessThanOrEqualTo(String value) {
            addCriterion("AUDIT_ID <=", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdLike(String value) {
            addCriterion("AUDIT_ID like", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotLike(String value) {
            addCriterion("AUDIT_ID not like", value, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdIn(List<String> values) {
            addCriterion("AUDIT_ID in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotIn(List<String> values) {
            addCriterion("AUDIT_ID not in", values, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdBetween(String value1, String value2) {
            addCriterion("AUDIT_ID between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditIdNotBetween(String value1, String value2) {
            addCriterion("AUDIT_ID not between", value1, value2, "auditId");
            return (Criteria) this;
        }

        public Criteria andAuditNameIsNull() {
            addCriterion("AUDIT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAuditNameIsNotNull() {
            addCriterion("AUDIT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAuditNameEqualTo(String value) {
            addCriterion("AUDIT_NAME =", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotEqualTo(String value) {
            addCriterion("AUDIT_NAME <>", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameGreaterThan(String value) {
            addCriterion("AUDIT_NAME >", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameGreaterThanOrEqualTo(String value) {
            addCriterion("AUDIT_NAME >=", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLessThan(String value) {
            addCriterion("AUDIT_NAME <", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLessThanOrEqualTo(String value) {
            addCriterion("AUDIT_NAME <=", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameLike(String value) {
            addCriterion("AUDIT_NAME like", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotLike(String value) {
            addCriterion("AUDIT_NAME not like", value, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameIn(List<String> values) {
            addCriterion("AUDIT_NAME in", values, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotIn(List<String> values) {
            addCriterion("AUDIT_NAME not in", values, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameBetween(String value1, String value2) {
            addCriterion("AUDIT_NAME between", value1, value2, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditNameNotBetween(String value1, String value2) {
            addCriterion("AUDIT_NAME not between", value1, value2, "auditName");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNull() {
            addCriterion("AUDIT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNotNull() {
            addCriterion("AUDIT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStateEqualTo(String value) {
            addCriterion("AUDIT_STATE =", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotEqualTo(String value) {
            addCriterion("AUDIT_STATE <>", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThan(String value) {
            addCriterion("AUDIT_STATE >", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThanOrEqualTo(String value) {
            addCriterion("AUDIT_STATE >=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThan(String value) {
            addCriterion("AUDIT_STATE <", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThanOrEqualTo(String value) {
            addCriterion("AUDIT_STATE <=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLike(String value) {
            addCriterion("AUDIT_STATE like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotLike(String value) {
            addCriterion("AUDIT_STATE not like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateIn(List<String> values) {
            addCriterion("AUDIT_STATE in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotIn(List<String> values) {
            addCriterion("AUDIT_STATE not in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateBetween(String value1, String value2) {
            addCriterion("AUDIT_STATE between", value1, value2, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotBetween(String value1, String value2) {
            addCriterion("AUDIT_STATE not between", value1, value2, "auditState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_cron_job
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_system_cron_job
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}