package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemClientTrack;
import topdeep.common.entity.db.SystemClientTrackExample;

public interface SystemClientTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int countByExample(SystemClientTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int deleteByExample(SystemClientTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int insert(SystemClientTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int insertSelective(SystemClientTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    List<SystemClientTrack> selectByExample(SystemClientTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    SystemClientTrack selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemClientTrack record, @Param("example") SystemClientTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemClientTrack record, @Param("example") SystemClientTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemClientTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemClientTrack record);
}