package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemAdminRoles;
import topdeep.common.entity.db.SystemAdminRolesExample;

public interface SystemAdminRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int countByExample(SystemAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SystemAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int insert(SystemAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int insertSelective(SystemAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    List<SystemAdminRoles> selectByExample(SystemAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    SystemAdminRoles selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemAdminRoles record, @Param("example") SystemAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemAdminRoles record, @Param("example") SystemAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_admin_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemAdminRoles record);
}