package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemBaseInfo;
import topdeep.common.entity.db.SystemBaseInfoExample;
import topdeep.common.entity.db.SystemBaseInfoKey;

public interface SystemBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int countByExample(SystemBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int deleteByExample(SystemBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SystemBaseInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int insert(SystemBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int insertSelective(SystemBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    List<SystemBaseInfo> selectByExample(SystemBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    SystemBaseInfo selectByPrimaryKey(SystemBaseInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemBaseInfo record, @Param("example") SystemBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemBaseInfo record, @Param("example") SystemBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemBaseInfo record);
}