package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemClientVersion;
import topdeep.common.entity.db.SystemClientVersionExample;
import topdeep.common.entity.db.SystemClientVersionKey;

public interface SystemClientVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int countByExample(SystemClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int deleteByExample(SystemClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SystemClientVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int insert(SystemClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int insertSelective(SystemClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    List<SystemClientVersion> selectByExample(SystemClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    SystemClientVersion selectByPrimaryKey(SystemClientVersionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemClientVersion record, @Param("example") SystemClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemClientVersion record, @Param("example") SystemClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemClientVersion record);
}