package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemRoles;
import topdeep.common.entity.db.SystemRolesExample;

public interface SystemRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int countByExample(SystemRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int insert(SystemRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    List<SystemRoles> selectByExample(SystemRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    SystemRoles selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoles record, @Param("example") SystemRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoles record, @Param("example") SystemRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoles record);
}