package topdeep.common.entity.db;

import topdeep.common.entity.base.BaseEntity;

public class SystemBaseInfoKey extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CODE_ID
     *
     * @mbggenerated
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CODE_TYPE
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    private String systemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    public SystemBaseInfoKey(String codeId, String codeType, String systemType) {
        this.codeId = codeId;
        this.codeType = codeType;
        this.systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    public SystemBaseInfoKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CODE_ID
     *
     * @return the value of t_system_base_info.CODE_ID
     *
     * @mbggenerated
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CODE_ID
     *
     * @param codeId the value for t_system_base_info.CODE_ID
     *
     * @mbggenerated
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId == null ? null : codeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CODE_TYPE
     *
     * @return the value of t_system_base_info.CODE_TYPE
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CODE_TYPE
     *
     * @param codeType the value for t_system_base_info.CODE_TYPE
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.SYSTEM_TYPE
     *
     * @return the value of t_system_base_info.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.SYSTEM_TYPE
     *
     * @param systemType the value for t_system_base_info.SYSTEM_TYPE
     *
     * @mbggenerated
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }
}