package topdeep.common.entity.db;

import topdeep.common.entity.base.BaseEntity;

public class SystemParamKey extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_param.PARAM_CODE
     *
     * @mbggenerated
     */
    private String paramCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    public SystemParamKey(String id, String paramCode) {
        this.id = id;
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    public SystemParamKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_param.ID
     *
     * @return the value of t_system_param.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_param.ID
     *
     * @param id the value for t_system_param.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_param.PARAM_CODE
     *
     * @return the value of t_system_param.PARAM_CODE
     *
     * @mbggenerated
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_param.PARAM_CODE
     *
     * @param paramCode the value for t_system_param.PARAM_CODE
     *
     * @mbggenerated
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode == null ? null : paramCode.trim();
    }
}