package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemConfig;
import topdeep.common.entity.db.SystemConfigExample;
import topdeep.common.entity.db.SystemConfigKey;

public interface SystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int countByExample(SystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int deleteByExample(SystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SystemConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int insert(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int insertSelective(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    List<SystemConfig> selectByExample(SystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    SystemConfig selectByPrimaryKey(SystemConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemConfig record, @Param("example") SystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemConfig record, @Param("example") SystemConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemConfig record);
}