package topdeep.common.entity.db;

import java.util.Date;

public class SystemBaseInfo extends SystemBaseInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CODE_NAME
     *
     * @mbggenerated
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CODE_DESC
     *
     * @mbggenerated
     */
    private String codeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.AUDIT_STATE
     *
     * @mbggenerated
     */
    private String auditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.ORDER_FIELD
     *
     * @mbggenerated
     */
    private Integer orderField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.AUDIT_ID
     *
     * @mbggenerated
     */
    private String auditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CREATE_NAME
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.CREATE_ID
     *
     * @mbggenerated
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.ROW_VERSION
     *
     * @mbggenerated
     */
    private Integer rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.AUDIT_TIME
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.MODIFY_ID
     *
     * @mbggenerated
     */
    private String modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.AUDIT_NAME
     *
     * @mbggenerated
     */
    private String auditName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_base_info.MODIFY_NAME
     *
     * @mbggenerated
     */
    private String modifyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    public SystemBaseInfo(String codeId, String codeType, String systemType, String codeName, String codeDesc, String auditState, Integer orderField, Date createTime, String auditId, String createName, String createId, Integer rowVersion, Date auditTime, String modifyId, String auditName, Date modifyTime, String modifyName) {
        super(codeId, codeType, systemType);
        this.codeName = codeName;
        this.codeDesc = codeDesc;
        this.auditState = auditState;
        this.orderField = orderField;
        this.createTime = createTime;
        this.auditId = auditId;
        this.createName = createName;
        this.createId = createId;
        this.rowVersion = rowVersion;
        this.auditTime = auditTime;
        this.modifyId = modifyId;
        this.auditName = auditName;
        this.modifyTime = modifyTime;
        this.modifyName = modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_base_info
     *
     * @mbggenerated
     */
    public SystemBaseInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CODE_NAME
     *
     * @return the value of t_system_base_info.CODE_NAME
     *
     * @mbggenerated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CODE_NAME
     *
     * @param codeName the value for t_system_base_info.CODE_NAME
     *
     * @mbggenerated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CODE_DESC
     *
     * @return the value of t_system_base_info.CODE_DESC
     *
     * @mbggenerated
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CODE_DESC
     *
     * @param codeDesc the value for t_system_base_info.CODE_DESC
     *
     * @mbggenerated
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.AUDIT_STATE
     *
     * @return the value of t_system_base_info.AUDIT_STATE
     *
     * @mbggenerated
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.AUDIT_STATE
     *
     * @param auditState the value for t_system_base_info.AUDIT_STATE
     *
     * @mbggenerated
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.ORDER_FIELD
     *
     * @return the value of t_system_base_info.ORDER_FIELD
     *
     * @mbggenerated
     */
    public Integer getOrderField() {
        return orderField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.ORDER_FIELD
     *
     * @param orderField the value for t_system_base_info.ORDER_FIELD
     *
     * @mbggenerated
     */
    public void setOrderField(Integer orderField) {
        this.orderField = orderField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CREATE_TIME
     *
     * @return the value of t_system_base_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CREATE_TIME
     *
     * @param createTime the value for t_system_base_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.AUDIT_ID
     *
     * @return the value of t_system_base_info.AUDIT_ID
     *
     * @mbggenerated
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.AUDIT_ID
     *
     * @param auditId the value for t_system_base_info.AUDIT_ID
     *
     * @mbggenerated
     */
    public void setAuditId(String auditId) {
        this.auditId = auditId == null ? null : auditId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CREATE_NAME
     *
     * @return the value of t_system_base_info.CREATE_NAME
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CREATE_NAME
     *
     * @param createName the value for t_system_base_info.CREATE_NAME
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.CREATE_ID
     *
     * @return the value of t_system_base_info.CREATE_ID
     *
     * @mbggenerated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.CREATE_ID
     *
     * @param createId the value for t_system_base_info.CREATE_ID
     *
     * @mbggenerated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.ROW_VERSION
     *
     * @return the value of t_system_base_info.ROW_VERSION
     *
     * @mbggenerated
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.ROW_VERSION
     *
     * @param rowVersion the value for t_system_base_info.ROW_VERSION
     *
     * @mbggenerated
     */
    public void setRowVersion(Integer rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.AUDIT_TIME
     *
     * @return the value of t_system_base_info.AUDIT_TIME
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.AUDIT_TIME
     *
     * @param auditTime the value for t_system_base_info.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.MODIFY_ID
     *
     * @return the value of t_system_base_info.MODIFY_ID
     *
     * @mbggenerated
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.MODIFY_ID
     *
     * @param modifyId the value for t_system_base_info.MODIFY_ID
     *
     * @mbggenerated
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.AUDIT_NAME
     *
     * @return the value of t_system_base_info.AUDIT_NAME
     *
     * @mbggenerated
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.AUDIT_NAME
     *
     * @param auditName the value for t_system_base_info.AUDIT_NAME
     *
     * @mbggenerated
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.MODIFY_TIME
     *
     * @return the value of t_system_base_info.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.MODIFY_TIME
     *
     * @param modifyTime the value for t_system_base_info.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_base_info.MODIFY_NAME
     *
     * @return the value of t_system_base_info.MODIFY_NAME
     *
     * @mbggenerated
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_base_info.MODIFY_NAME
     *
     * @param modifyName the value for t_system_base_info.MODIFY_NAME
     *
     * @mbggenerated
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }
}