package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemParam;
import topdeep.common.entity.db.SystemParamExample;
import topdeep.common.entity.db.SystemParamKey;

public interface SystemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int countByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int deleteByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SystemParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int insert(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int insertSelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    List<SystemParam> selectByExample(SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    SystemParam selectByPrimaryKey(SystemParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemParam record, @Param("example") SystemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemParam record);
}