package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemExternalUserRelation;
import topdeep.common.entity.db.SystemExternalUserRelationExample;

public interface SystemExternalUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int countByExample(SystemExternalUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int deleteByExample(SystemExternalUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int insert(SystemExternalUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int insertSelective(SystemExternalUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    List<SystemExternalUserRelation> selectByExample(SystemExternalUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    SystemExternalUserRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemExternalUserRelation record, @Param("example") SystemExternalUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemExternalUserRelation record, @Param("example") SystemExternalUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemExternalUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_external_user_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemExternalUserRelation record);
}