package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemClientTrackDetail;
import topdeep.common.entity.db.SystemClientTrackDetailExample;

public interface SystemClientTrackDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int countByExample(SystemClientTrackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int deleteByExample(SystemClientTrackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int insert(SystemClientTrackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int insertSelective(SystemClientTrackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    List<SystemClientTrackDetail> selectByExample(SystemClientTrackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    SystemClientTrackDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemClientTrackDetail record, @Param("example") SystemClientTrackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemClientTrackDetail record, @Param("example") SystemClientTrackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemClientTrackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_client_track_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemClientTrackDetail record);
}