package topdeep.common.entity.db;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import topdeep.common.entity.db.SystemHisMsgPushDetail;
import topdeep.common.entity.db.SystemHisMsgPushDetailExample;

public interface SystemHisMsgPushDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int countByExample(SystemHisMsgPushDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int deleteByExample(SystemHisMsgPushDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int insert(SystemHisMsgPushDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int insertSelective(SystemHisMsgPushDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    List<SystemHisMsgPushDetail> selectByExample(SystemHisMsgPushDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    SystemHisMsgPushDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemHisMsgPushDetail record, @Param("example") SystemHisMsgPushDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemHisMsgPushDetail record, @Param("example") SystemHisMsgPushDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemHisMsgPushDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_his_msg_push_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemHisMsgPushDetail record);
}